# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &devji age1tsv2lurpjzyx9ng6hcc4dff23lvv7tqkyyxz5zlpx32egu2c9vfql9m008
  - &servermb age1ywan3hwg4v306e3gk4sjzfvjfxru432kgr3xlmwu77nkhgsjmfuqr7lktd
  - &mbdevji age15ptau7jyv6kcwz39vcfzxpw95p97l5r7uywkcl5g83gqxuhh7q4saggagy
  - &sopsposeidon age1ezs5s0mx7pcmv0cq6lhvxqtrgx9shrenpxuqyny3m52rg4a6vuxq9ucd7c
  - &hposeidon age10njuv5050y6wvxq0a9vpvxwrd4scr34cxrxmzz3cl8p7xwjydqhq358af6
  - &sopsacer age12yhcg6c7spluq7z0dsgduqfvvcqzyz0a5an3zsndecuc0h2w3ftseyzlad
  - &pengsops age1cpkcemzhdkc5zmghdx63qv0km2t934raj6fs0ff7uftet00fh3qqjc8wq9
  - &minyx age1fer9mjcr3cdys3n8cywtuew2cdg4fz20srgn08rh4wfjezk7z4yq25dvd5
  - &guckloch age1aq6fer9unde6xwjw587qzc6e6cfe4wlu2xvcah7vjqrkptkd7gtq69v38r
  - &lunarfall age1wvrf6uclae5ald5uk5lvjyj9pgpc56tpy9vannv7wmy0s092850qk2mn0y
  - &schneeeule age14wsec4ypsqzx075mxw6nen6htdm6tmsu3artlf4jas7jk02zmecsg7kseh
  - &leakynose age1s2vtxjp0hjrrjulx9qf2gejn9xkd5y4gu2m0wrxw5vqw7cf2ea3qkusze6
  - &schneeeulehost age103h35vrcud7a8mk0fzegzlyazq0qtsgggnzyxf4vf3z2qdspxgvs9zhdy5
  - &acersops age15mzmhlt5hh5z94843e27rqev4955v3gkcwqacr4ueyxegzav94kqvz0c43
  - &minyxhost age15g3grw9k0mnpvst4r2yjdfhpa9sc66wrtl7gskypwpyzmffjvu2qhakyq9
  - &orb-cassini age15ptau7jyv6kcwz39vcfzxpw95p97l5r7uywkcl5g83gqxuhh7q4saggagy
  - &acersopshost age15mzmhlt5hh5z94843e27rqev4955v3gkcwqacr4ueyxegzav94kqvz0c43
  - &usbares age165pm2te09z0kzjwrvwcy9qdvycpqlqw2v7hxmv9u7tcy9w3ld3cq0nughq
  - &usbareshost age12wmg9wmatu5mlyjqs0afgdj4uu7m6flc05anmq0v0a3m50zhpswsyjhf7a
  - &alarm age1juyqqqcntxf5affyt4ukr2fyerw6mexw08w3y8tyqjkm27k3hd8qpax2y5
  - &ares age1nqdx5a80wy6d3hjsldhhe5y4ltrfv3zr9m3cdrekcxha0hg7g5usxj482d
  - &areshost age12gezpwjwq0ln36gt22h3hp6v2tsf5df4sgrr7x4g57sa83dc6unsft55zx
  - &thinsandyhost age1fgrg9t27a39falklr9375p3q6hcrqm52rdges83zawzzpnev3cvq7fgfgm
  - &thinsandy age1q6klnp8k9282fjxlweu5gmkxpt4pxzyumkk3q8hdeunz8w3ns40scn7q8a

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *devji
      - *servermb
      - *mbdevji
      - *sopsposeidon
      - *hposeidon
      - *sopsacer
      - *pengsops
      - *minyx
      - *guckloch
      - *lunarfall
      - *ares
      - *schneeeule
      - *leakynose
      - *schneeeulehost
      - *acersops
      - *minyxhost
      - *orb-cassini
      - *acersopshost
      - *areshost
      - *alarm
      - *usbares
      - *usbareshost
      - *thinsandyhost
      - *thinsandy
      gpg:
