# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &devji age1tsv2lurpjzyx9ng6hcc4dff23lvv7tqkyyxz5zlpx32egu2c9vfql9m008
  - &sopsposeidon age1ezs5s0mx7pcmv0cq6lhvxqtrgx9shrenpxuqyny3m52rg4a6vuxq9ucd7c
  - &hposeidon age10njuv5050y6wvxq0a9vpvxwrd4scr34cxrxmzz3cl8p7xwjydqhq358af6
  - &sopsacer age12yhcg6c7spluq7z0dsgduqfvvcqzyz0a5an3zsndecuc0h2w3ftseyzlad
  - &guckloch age1aq6fer9unde6xwjw587qzc6e6cfe4wlu2xvcah7vjqrkptkd7gtq69v38r
  - &schneeeule age14wsec4ypsqzx075mxw6nen6htdm6tmsu3artlf4jas7jk02zmecsg7kseh
  - &leakynose age1jykxrxauzv92xk0rscav5pd52dhzegzuxrha3c8unx2x7ktsm52s0tlfqk
  - &schneeeulehost age103h35vrcud7a8mk0fzegzlyazq0qtsgggnzyxf4vf3z2qdspxgvs9zhdy5
  - &acersops age15mzmhlt5hh5z94843e27rqev4955v3gkcwqacr4ueyxegzav94kqvz0c43
  - &acersopshost age15mzmhlt5hh5z94843e27rqev4955v3gkcwqacr4ueyxegzav94kqvz0c43
  - &ares age1nqdx5a80wy6d3hjsldhhe5y4ltrfv3zr9m3cdrekcxha0hg7g5usxj482d
  - &areshost age12gezpwjwq0ln36gt22h3hp6v2tsf5df4sgrr7x4g57sa83dc6unsft55zx
  - &thinsandyhost age1fgrg9t27a39falklr9375p3q6hcrqm52rdges83zawzzpnev3cvq7fgfgm
  - &thinsandy age1q6klnp8k9282fjxlweu5gmkxpt4pxzyumkk3q8hdeunz8w3ns40scn7q8a
  - &ancientacehost age1ageqwpdaf0zkkkc3xqf3qag577fm80cf8vqc5glkz6fqjjp7jpss8t590l
  - &ancientace age1pk08qp3exeaw8ky7vs3xtxsuw55g8nrsp8j8pj4xar8ynngv7q9qtywkkm
  - &mtfuji age1cpped4xh57c2zrguv6y2sqy526lnpklmruw7leu50xxuclmux5askrhrry
  - &mtfujihost age1tgek4uvpjy2hls5uf80c4sxdshgwhj35fyrcervgefec9rwz05nq59cfew
  - &sandylaptop age160ke2yrkx3h34l8h8xhqktcwtwhsdzfcg7h3ca0gsl77hwzwv5rqwy0gwl
  - &applevalleyhost age15rlqjq7nzc0xnnq5z32ugkkg4dzhxjsg3hxstlh0gygq3rffcvlsfqruj0
  - &applevalley age1afuz306fl0vcp9lje6exyczwncnw5rklef3kq5d5mfmpy7f68ejsp99v69
  - &kali age16q43vrn59pwjfpuwygmqg98enu063dvveazrlr02zcf339wxj3qstsxywq
  - &penguin age1lxkrls0zrq24c3crg3ffpsllk30tu6amk5munfmfcw3rhev9ppvsatm0vh
  
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *kali
          - *devji
          - *sopsposeidon
          - *hposeidon
          - *sopsacer
          - *guckloch
          - *ares
          - *schneeeule
          - *leakynose
          - *schneeeulehost
          - *acersops
          - *acersopshost
          - *areshost
          - *thinsandyhost
          - *thinsandy
          - *ancientace
          - *ancientacehost
          - *mtfuji
          - *mtfujihost
          - *sandylaptop
          - *applevalleyhost
          - *applevalley
          - *penguin
  - path_regex: /[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *kali
          - *devji
          - *sopsposeidon
          - *hposeidon
          - *sopsacer
          - *guckloch
          - *ares
          - *schneeeule
          - *leakynose
          - *schneeeulehost
          - *acersops
          - *acersopshost
          - *areshost
          - *thinsandyhost
          - *thinsandy
          - *ancientace
          - *ancientacehost
          - *mtfuji
          - *mtfujihost
          - *sandylaptop
          - *applevalleyhost
          - *applevalley
          - *penguin
        gpg:
