# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

menu:
  - rebuild
  - nwmount
  - browse
  - edit
  - git-quick-push
  - exit
rebuild:
  - nixos-rebuild
  - darwin-rebuild
  - exit
browse:
  - browse-notes
  - browse-internet
  - projects
  - exit
edit:
  - edit-global
  - edit-secrets
  - edit-sops
  - edit-sops-config
  - edit-home-manager
  - edit-shell-config
  - exit
update:
  - update-flake
  - update-sops
  - exit
tasks:
  default:
    cmds:
      - task $(cat Taskfile.yml | yq '.menu.[]' | gum choose )
    silent: true
  rebuild:
    cmds:
      - task $(cat Taskfile.yml | yq '.rebuild.[]' | gum choose )
  nixos-rebuild:
    cmds:
      - sudo nixos-rebuild switch --flake ~/nixconfig#
  darwin-rebuild:
    cmds:
      - darwin-rebuild switch --flake ~/.config/nix-darwin#
  nwmount:
    cmds:
      - sudo mount.cifs //192.168.178.1/fritz.nas/External-USB3-0-01/ /mnt/y -o rw,noserverino,username=jisifu 
      - sudo mount.cifs //burgernas/usbshare1 /mnt/z -o rw,noserverino,credentials=/mnt/y/documents/secrets/credentials.txt
      - sudo mount.cifs //burgernas/Shared\ Library /mnt/x -o rw,noserverino,credentials=/mnt/y/documents/secrets/credentials.txt
  browse:
    cmds:
      - task $(cat Taskfile.yml | yq '.browse.[]' | gum choose )
  browse-notes:
    cmds:
      - nvim ~/Documents/Obsidian-Git-Sync/quicknote.md
  browse-internet:
    cmds:
      - open https://duckduckgo.com
  browse-projects:
    cmds:
      - open https://shaoyanji.github.io
  edit:
    cmds:
      - task $(cat Taskfile.yml | yq '.edit.[]' | gum choose )
  edit-global:
    cmds:
      - nvim ./modules/global/global.nix
  edit-secrets:
    cmds:
      - sops edit ./modules/global/secrets/secrets.yaml
  edit-sops:
    cmds:
      - nvim .sops.yaml
      - task updatekeys-sops
  edit-sops-config:
    cmds:
      - nvim ./modules/global/sops.nix
  edit-home-manager:
    cmds:
      - nvim ./modules/global/home.nix
  edit-shell-config:
    cmds:
      - nvim ./modules/global/shell/default.nix
  git-quick-push:
    cmds:
      - git add .
      - 'git commit -m "chore: update"'
      - git push -u
  update:
    cmds:
      - task $(cat Taskfile.yml | yq '.update.[]' | gum choose )
  update-flake:
    cmds:
      - nix flake update
  updatekeys-sops:
    cmds:
      - sops updatekeys ./modules/global/secrets/secrets.yaml
  exit:
    cmds:
      - exit
