version: ENC[AES256_GCM,data:Wg==,iv:AkAQEQlnW2ucgqlB64naB1aCWG4HqdhwIGv3DjOnhAE=,tag:7nNBikC1/oiU3PnmacyTZg==,type:str]
vars:
    GREETING: ENC[AES256_GCM,data:vSUkpGsgygXRkh11og==,iv:gG8Rria1+jHVjwFzmnnRwzmW6R4e9BKZYP/mpCccyos=,tag:cT5+4RCCP24sWD8i1DGIlg==,type:str]
menu:
    - ENC[AES256_GCM,data:r5D+PVzzCw==,iv:q9ayGaS3u2fVHtSloLeu517ma88w6CVUYhHrByMEWtY=,tag:EfWUFWTqdtPawR29Xr537A==,type:str]
    - ENC[AES256_GCM,data:lBUQwg==,iv:Pz/2HMtfeM4roAAQ1AkKjuJN4dLCD4YRTYFOmwaScsc=,tag:Mewllgrha7knCZeCBOZZGA==,type:str]
    - ENC[AES256_GCM,data:LMFbqlKO,iv:4bPY4k1M/Bu7ShSv8nUqOdouKHQqEa9VT6PxTi67G/s=,tag:XGlnSua88Gk4CSaYJOtC/A==,type:str]
    - ENC[AES256_GCM,data:B4TDOMQ/WnW+314=,iv:GvoR+N8LLFah0oQz1LrZKC+UL0lQIS7n09XoPzLY0To=,tag:h+t3q9jOqwwXkCb/tSqtDw==,type:str]
    - ENC[AES256_GCM,data:F/0hWrRN,iv:wWOpQ3gfXC5SjfX7BuH9lrfw9V3Uls4aWezQn5wacwI=,tag:G7wtT2T4RdEXFTZQSm+CHg==,type:str]
    - ENC[AES256_GCM,data:BfqjGg==,iv:vAMn52DvLXzANxbVFA5g3HmRBwrZyXOjRYpAeZUw74Y=,tag:qQgRmZbG7gPCf5iHxDtJfQ==,type:str]
load:
    - ENC[AES256_GCM,data:e3+BLrHFIFCX,iv:+qwnQkW9cMDPkWDmV7XysOvro8HTV2mYff5aM36lhoA=,tag:K7tS0Li4fKBwxl4fWzDKmQ==,type:str]
    - ENC[AES256_GCM,data:Um61nC3HGQ==,iv:krK+Mgm848jXnNPYj5UQHc4kuysMzIMfICwFV45Peoc=,tag:TvFGeaHWL1tpZDOQHlzsOg==,type:str]
    - ENC[AES256_GCM,data:UnqRxg==,iv:EvC25+n6ySo0B89FzTKvgkWF3mebBsbq3BhG+1Tz94I=,tag:ceyMhbarQRXcGfNPu/gqTQ==,type:str]
rebuild:
    - ENC[AES256_GCM,data:YDDqxNVdoHUb9RJnHg==,iv:ZK2DN/WokTdhelxVrlrWsWoOB5FuZEJfaOUzoM0ekx8=,tag:hnm2ekWKbLxQqFOUH44EKA==,type:str]
    - ENC[AES256_GCM,data:Yimeo+UYw1l0FY6Ef1I=,iv:FZDO2oLGhfcHG85UomzscIY3i7CZHwydn61xfYo9cvo=,tag:cxZbbzF0yKqwTJgSFubqbQ==,type:str]
    - ENC[AES256_GCM,data:S7JzM8BtHpLeYCTMsf5a44CSPw==,iv:7vEp9CR48NPsKLP0J3mYzI2xovlj1OluTe1gX0sZBGY=,tag:cCTwWI2ntaf/1eob8Mcwew==,type:str]
    - ENC[AES256_GCM,data:rPtmDw==,iv:OSRfttdwW6KNLvUo53C13eQ7NseZTBMkR0xGZWjhDw4=,tag:4NvBzUJLL5M/DClHvMTTRA==,type:str]
home-manager-switch:
    - ENC[AES256_GCM,data:Wv/EoYWoffzC3mq7,iv:Nhb9rew0yftHK/euecSkYKAN+pYt3SRywADrg/AYB2I=,tag:awMDLWQbhFkDboY0IrO3vA==,type:str]
    - ENC[AES256_GCM,data:UpwOxilevFcnQflBzP2ADBqrsA==,iv:+5OxNKXLU25O+f8n8a0bPPzACLp0XWZ/1Gh0X/QNboA=,tag:NRf8DdkjpmZYNbalInSdUQ==,type:str]
    - ENC[AES256_GCM,data:GbhkW0MilbDo0A7pcQ==,iv:LElU6ey0a2pY3ckDsXo10FC2ct51qLsk0SqYzCL0CD4=,tag:wTz/MIHmpIHidgEtsx8SCw==,type:str]
    - ENC[AES256_GCM,data:rP5xVLvplw==,iv:vN33vHs+Bw5Cn9OVEgSrGviR8JSV2pu8tMDZ4lRAWPQ=,tag:WUlBbA0a3tk6RzPgs/1+1Q==,type:str]
    - ENC[AES256_GCM,data:Tlmr+w==,iv:RNPF3Jqw4qeM48hvbuC8WJ0e3A5yRSiXp0qj95AUE24=,tag:tIwnjEPc1WRjmZlcsbldJA==,type:str]
browse:
    - ENC[AES256_GCM,data:3xQ0xp6qVJJaXU91,iv:nNnavemlY58zd9/FAfXXKtsQqhFKBgYjNE86ODeNuP8=,tag:Se25FRXqsJovKzBjC7Qz1Q==,type:str]
    - ENC[AES256_GCM,data:M8W1WmMtR0eNUTVm+mj5,iv:QfLmfdhbXhWe/UN55QKD8xBSJgyuN1N12+DSPuosZp8=,tag:tjyW7BbMtJyRXlkHSbJKRQ==,type:str]
    - ENC[AES256_GCM,data:trs+rc2bpWU=,iv:6vYQ2fCExPXyniw93SbwAp8pdC5XeoDnMzRQQL8uJLQ=,tag:8U4/7W1iWoVX+slDJE9PRA==,type:str]
    - ENC[AES256_GCM,data:wSZ55w==,iv:g+q6DHNpaQg0YHGmXwxypQYslI/CfzBQry/VS8gUCe0=,tag:p0lrxVKPyoLRv6WGxzOX7Q==,type:str]
edit-config:
    - ENC[AES256_GCM,data:hwDx+YQl0/AtW9FOng==,iv:Mi0GhzORJzo39+49fjMskXui6lnqZJRN0XGX+/gnr84=,tag:SPbKmTFs84y3/E/lJzV8hg==,type:str]
    - ENC[AES256_GCM,data:WEfcmocy8kvok50=,iv:sWuxSZBKIJ4SXqRzHcHR9QLfWAwWRF5fsX2eSEapvuw=,tag:iOSMnmc/iKvKiqui863UnA==,type:str]
    - ENC[AES256_GCM,data:DlNdKpo1hqnVA1gi,iv:B0enaeJSLaeJksKV6MypQE0eFsLNhB70rpEVYRUtvfM=,tag:uTKdQKHWze2Ip1v3uw54oQ==,type:str]
    - ENC[AES256_GCM,data:en2cz80EbVR/,iv:tU2QvJewXACt0tfs5VyDH5jXLShZcuRmezMucWokhUE=,tag:dlsz4jozBzfs0Y9LCOWooA==,type:str]
    - ENC[AES256_GCM,data:oo/0oaWlPoQPj265TVYjwQ==,iv:TFXvO7bssS2Rfz88JfDjtRzNdpJLGRAi4+qN+b0LH2Y=,tag:Xj8tkhpuU7Rot1UTJ4hVjg==,type:str]
    - ENC[AES256_GCM,data:7RN2+8Tf/acVY2MrB1MxM9s=,iv:nrC4ljp/meBp74SlXUt5BY4usWD+fP+jlv3G+uk2T5g=,tag:/VPI0UQsFsABZjpRpIhaAg==,type:str]
    - ENC[AES256_GCM,data:0ki+JFr5JnOVwDLYucYY1EM=,iv:pYtmN52/0ZX+3iddhP7uHsLZP5LAr7oE6cUnoKULqls=,tag:EYXFD85a+MLca9Wxx24G3g==,type:str]
    - ENC[AES256_GCM,data:c2pF+Q==,iv:znWJ3zQeGaZyFRXO1Hb9Hn0wfnyeHShPFcuhYGamOuQ=,tag:msF3bP6wyPUdL7Tyl2m9UQ==,type:str]
update:
    - ENC[AES256_GCM,data:BH7tx3BBM3EyasJBkuQ=,iv:55BP2ZjYHW3tMflTgQzKXBWflGzsrOqeSX1vMVmpbtU=,tag:XLnxqON3N4Ht8Rvumd8hvw==,type:str]
    - ENC[AES256_GCM,data:4ylpcS2zzVJn0z3lzPc=,iv:FfKNvRPR5XiiJgPGISucnhCJ0DLhYmYQh6+PzkHTKU4=,tag:r7H49XBqxgf58X7B6PORmA==,type:str]
    - ENC[AES256_GCM,data:MSpN1eAUFLOTQXb9,iv:nmOiviJ0FXvJQkVj0cULI9F/ZTth77AIqQkemp3AMhM=,tag:2aR3Xbk+7AnBpoDWVkRNkg==,type:str]
    - ENC[AES256_GCM,data:+8GPRCsDt8SZ5VcsaPs6,iv:kzUCKCr631kjQxo4fKGN7DROr4Fpy3dGIBD/tg7mq8Q=,tag:cvRvEml9XRS6N0fY+FcwIQ==,type:str]
    - ENC[AES256_GCM,data:B3fRCg==,iv:jxoNuwKPnaXSUDTbG7tVOhZDmXSbkzh7rv7r2E7+CH4=,tag:+151YV8/VClrAPIZkqkdYA==,type:str]
tasks:
    default:
        cmds:
            - ENC[AES256_GCM,data:UL0NUBScXO998XL91IIEMM72zxp1Ww2mWDfvnYg6U1jc1+NSVUpX9OAWfXp5aEMu+RSpa4ss,iv:MOz/2wtz6WrzkTTzib5k3Au+z51+F5eku7gxoLtuSrY=,tag:IatpMObfus900eT59BIO3Q==,type:str]
        silent: ENC[AES256_GCM,data:peo3mA==,iv:rF178fkyiKK0q6vD2Uq/7FAeFazJQqD1FjLUqB2gnmA=,tag:u03pa69t+4qDoGcBG6eNvg==,type:bool]
    rebuild:
        cmds:
            - ENC[AES256_GCM,data:O2hWjbEM17Y9hp4mRFU6hB5s8hLlXb6y/5Vygbx8URy+bX1IdriwQy7iUsfd5LaVf2S+jG/P77oz,iv:+l73atuntQeKfu0gaS6p/6eywlmlaKA8GpiQq0IbWY0=,tag:tRVvZVZrhtPGzq5TmteurA==,type:str]
    nixos-rebuild:
        cmds:
            - ENC[AES256_GCM,data:sEP1UDxII4oC+OmqEaYJvzhu67Uvo7Ondhi2d+XPQWYqpoebqWXAeevMNdDhu0RzAWgRlxt3+oLVLNTQPIS/,iv:w6KLxQzD4nR5XTCZmKXOsGTh9DnbFQWyLTeMm4dyjFU=,tag:Y4lGmdKG1GE70O/eUOEf5A==,type:str]
            - ENC[AES256_GCM,data:vaHNIxMHvbLw0HWMIA==,iv:3sR2LnHBySj2xeZCL7ypJ3FbfFyasrNuFipEDFQdjNs=,tag:qVWhiq5Koe/qVLGKwUQzjA==,type:str]
    darwin-rebuild:
        cmds:
            - ENC[AES256_GCM,data:OmdA0ELLctmwwWsKeU1bUBHDrg7vdPJmKl2glx+IoIIRDUfjoISLRlPoTYQi/CZAzhxRq9W/W11e78A=,iv:SwTt07vJEKaYqUzDvfw4qVQiz0dvueADkU3BsO7jfMg=,tag:9bmMOxPbRyRne8DxTibavA==,type:str]
            - ENC[AES256_GCM,data:4YXrzg1g77D7UzqaUQ==,iv:Tw63OdHjPYd8Ts+Emwl/nVnP2qB80Zp8h0UEJE73PSo=,tag:xBWm/2cTJQ9O+hKlllOt5Q==,type:str]
    home-manager-switch:
        cmds:
            - ENC[AES256_GCM,data:1Mu/mAN0g/H1spYxl8qv3M2U4Us/2Sj1x/pAseDHU3DZj+VYk2ERKy5MV2f4aAUTVtiSrQHtQOhdcEa+iQ+m15nZ6i9J,iv:6N4+G3zfHLPIbHm+WSNvdUYzikS7EafVVF92mdbHRG8=,tag:2sp9XKUTZ4ifzQ5mysMtMg==,type:str]
    aceofspades-rebuild:
        cmds:
            - ENC[AES256_GCM,data:uoXYyjeL81JYZ+X6OOAOQw35QmyM6RnONUiGzaGdST+VKznYx4vV1DT7+XMfqIi2OZ9oRRQnQT4T1YgnKJwC1WUdZ0M=,iv:Vl7FHYE2L82WdZ7XOCucOMOk30YZvhaYeeyuJQ/AUfs=,tag:jDkSyJKuJiOWXf9gSARfcA==,type:str]
            - ENC[AES256_GCM,data:apfiQYpO4QgvAhkIow==,iv:TsGUOSDy1yl3/5hWb3R4yzC0+P9jFG5EKAU03T4kzdU=,tag:55vKMf8BA5acc49M5XwvQA==,type:str]
    alarm-rebuild:
        cmds:
            - ENC[AES256_GCM,data:mdbJDj+ghcbcnctrfW0xUkvIEUZ711Udb1UfOLigbo3FN9nvqI+U+VYyK9qAxtbeNrCIrPJizcrpAf7fYUI=,iv:OVpuW9oD19PkrZRh4iLijpdNrSbf9O9L8mAv9INh3HE=,tag:5cL2M4cTtyjhqE/mp0ZoOQ==,type:str]
            - ENC[AES256_GCM,data:ksLgchiM9jzQsDDRzQ==,iv:+ajMJUdQWzbTSNiGczri9AAEbX/1uQyh407D3qyRipU=,tag:jcOFcXyQmyv/AIrHrL7fUQ==,type:str]
    heim-rebuild:
        cmds:
            - ENC[AES256_GCM,data:7ekE/93UJWO5v2mIVEYL8Ppj4J++8/0NIOdq2BUSbjAs4n+vQE0qPF3DiGOagbSJ70OnrW9vmsO+1zwzXg==,iv:sVu1MXBQXLH77nTcZUcXqK5rTlQgrwFbVAa745TRVhk=,tag:458gxLgNWuNR+0WrVjUzMA==,type:str]
            - ENC[AES256_GCM,data:tjwAtrgcS5ywFRo+Fg==,iv:gibuHL3JPCMJHtmVldReVN63LuwZj6glz1wUlKGYNf4=,tag:8RNWTre+cRpwfpwmEY9MBA==,type:str]
    load:
        cmds:
            - ENC[AES256_GCM,data:/ubzVfdMd8sQCjSogb0bOMB91Phj5ptkYR2BKtr3mj9ilDoNsbQ4pZgx39S0dcMd+QlQ9Qhw,iv:+LAH+OKLnGeB7bg4cHfqwc5iS5X+AX+gQQ+nw98U+4U=,tag:aVuMxE4es/2LXy2cKNQJ0A==,type:str]
    load-groq:
        cmds:
            - ENC[AES256_GCM,data:BSaC37G0f0+htxSMZWdlplIbc7VZ6SBM8/kxner744/3bMBQFxJZqamU6hCpSXvnHXJSofnM311wSubho6+F0BzSaIz87KrRwieS6rXl/vfjgEquDmd8tE7tw0vK/Wny7cwnO6oUrdEI2U5RrsDLZ0th,iv:WV4EbzZOjxY4F1g+91fkgmf7R7suxCcop8cbEoEA/YY=,tag:Jd0BDp6pg98HcPwnE1m4DA==,type:str]
    nwmount:
        cmds:
            - ENC[AES256_GCM,data:xTpVaipp9yS465sJaIQPklDLE8Yh0csS+INQ3bqi6lohaOpzMVb3J1mX9Kb15dunbYYsV5GwKSp0v+SZUU0AGW8LgQY4aDxfQsjdECk2Np4iQqMta41U2zyrL/uNdz0SXzCjA2IE,iv:aMaw1cVDQFVqlp0tmvf7JSQgVQbVWjqomhtPX14XiIc=,tag:3+aD4HKHaWwf3dj33URTNA==,type:str]
            - ENC[AES256_GCM,data:/0W1tZfjzJ4ZoA4F5UX8ja8aG10qZwhXWmHIkcnQmth34kOw+cI5O9XTtLl5MwHnTAE3KevfasPiIs6OlqkrcMikttB9joxZE7QPzzTjfmUSlX0tM/P3zdJgRCOLNdLhVJvB0FXu2/368Q2MdvQi+BPRaQ==,iv:i2diudOOL5Of9zjivFaHGT8dAaXW5rDdTS/z+lHwbqg=,tag:riDoBbO/1zDyUVEqANkTGw==,type:str]
            - ENC[AES256_GCM,data:7jJOaHcbHV1idaK3Zrm1q8GCHPlMUo0e3v8lTDanN/9mFB/w7WYeUM0BKZkVMi2mI8TDQTQ78ssP1tg6U3xqx8MfWFdYDc6hJIDL+nV6Drp4xf5EJmRuIwHxjWDKOnu11GMx2Ai+sDyAOOlvp91IseTOAdYItYkSrg==,iv:IlB4/W4pU6VNNw5f4vs+cFhibW+T5tASjX9kgJE3YOs=,tag:wLvAUgROI6mJXk725p98PA==,type:str]
    browse:
        cmds:
            - ENC[AES256_GCM,data:abns0B7JEaZRuRuNq/HUgPPj+yc2qwhKzw4lfjXjnu09QoqT7QhYWaS9+SGXyyymLhEgs3Jyfhs=,iv:6S6zjrOsiBb3kJZEqxrduLPezcN0IKrHp1E19YXfkfg=,tag:nOnAk4+07VktJwYPVPrnHg==,type:str]
    browse-notes:
        cmds:
            - ENC[AES256_GCM,data:DT/ALFVHWdkmCOl2f0fOrSKrPsrqq5eQTabgqb7uZjcnuh+3A/RuBz5gwXMQM9Cbd/k=,iv:+D/n5m1okma14QM70pNgYCiBF5qE90ghXzED50W8+jg=,tag:D2Emczeo92ndrIE3nykPIg==,type:str]
    browse-internet:
        cmds:
            - ENC[AES256_GCM,data:KUyqTWS5JIhBbcTfjzwVDPkxKw/3oWE3Lkli,iv:etboXBDRxdNhLX/f/iv8Z3atpHliduxDbU5HYtIG7Ac=,tag:/EFIVZ48h48peJPZFGA2IA==,type:str]
    browse-projects:
        cmds:
            - ENC[AES256_GCM,data:45/OdGHRQdzs7VnuqbGlTEt7Y/g3Y1CK02DJjqxJvu4=,iv:bB4h71GEE/yb+I7R5kqvZqu81aAyZucLpLl3ykEeWFQ=,tag:93VYxFmC9/JvI3FcVxg/KQ==,type:str]
    edit-config:
        cmds:
            - ENC[AES256_GCM,data:b/ja0sxTSVlAJFuEhdZ2CJMHG2QUHxPxOQAhFhyxhHpf8N9l6RpdT1RXRXqNzvvQeAfDk8KqC28WH++wbQ==,iv:NmGBlKU4G59sKgMdNXyw4HYYpiU+iPB+lzYFFKhoBIg=,tag:Qh3i9golUy020jNqwoPbOQ==,type:str]
    edit-taskfile:
        cmds:
            - ENC[AES256_GCM,data:AE5M1m8WTjAzX+J+uX6zVIPEm0ukhKBRGlgqwFPBX7zMe6hZm7szsZi7uhcLIRX7,iv:EF3pd6lyv+DEWOrLl3ojeTEJcibKQUQ2UQ0xj+SOvVg=,tag:bNJtei01IXQKZBFb6w2omQ==,type:str]
            - ENC[AES256_GCM,data:DV+ke9N/ctA3HhcUspSTPm/8u4cInSAFRaeRYa/2pWvzbZGiT+5n1SrjOS/pGg==,iv:1K9ErFaR8BwsJeu0+qri5Mxw4qGfYAnAx06NpQp8Dt0=,tag:kys4BSvn3X9JbASJQ6OJzg==,type:str]
            - ENC[AES256_GCM,data:isl4mCv5BYIMF28SamP/21SkPkiamb2uRR1uL7o8p44=,iv:cAMO6wXYWFdfITU8tRn5mHsvqlnS4sVDHoELTlW5V+A=,tag:vJ8fVil/cWZGobNMc8ViaQ==,type:str]
            - ENC[AES256_GCM,data:g9B9Ok/tJ5ro2Qo=,iv:tDSeg1WmZEEwtPkB43pmTabT6BMkEnQUpYm1MMVjY7Y=,tag:D87khWqgXx62O7bX2GOHYw==,type:str]
            - ENC[AES256_GCM,data:DuZ+m09FLXIQQH3PBg==,iv:KX0CCAnAtlmtPg1N7N05mc5NZJEAH0jraV6aEsJJ8Cs=,tag:MXxq0Q/2XZXaaYbnoHRLtA==,type:str]
    edit-global:
        cmds:
            - ENC[AES256_GCM,data:A/Lt2lZJyMYUFBbYsfeC8fKlsdQ2kpPN2HWAnnKH3C+gB78=,iv:x13lpcajIZnDiMrlRAvFwLJHXNZxSakYuR7DXFTxsgo=,tag:23YIeSc8MbdytLximoxFtw==,type:str]
    edit-secrets:
        cmds:
            - ENC[AES256_GCM,data:jAR5bbulX/SOe7TzTP8w6kRIkT2cW8b67YcOYCl75hL+q/84T4encgfCNQsq7jg=,iv:zhnlfuy0WM8h1odJ+/w1bhgi4VBeJDwVbb6UI/qnEGc=,tag:40pqicFF03mFBwVNyROQ6w==,type:str]
            - ENC[AES256_GCM,data:emlEkAQ3yLyKzR8yKO4c524kohmp3epAUm+BR7KrxWO+0/+Hja+PGaf3AyuZ,iv:6jEuO7re0eEp21/abxAx9+cc0GJBlzyY8vRFAj0cw8U=,tag:VO2ylrjOCpm7hJhpcI1A1g==,type:str]
            - ENC[AES256_GCM,data:iGDmClCjqTwQfEXDzYpijGcFldkMzzGtH8dVHkoV0Q==,iv:Uupqg63u8e74C6Kh0yNTYaiLleICtNqU86XJxFWzrHA=,tag:5UL/oyx7QIv3stU7gWAmFg==,type:str]
            - ENC[AES256_GCM,data:E8kS18Jqdn+3yM0=,iv:XFfdi7HhpRbrOvfSntirsE7ZOlqjAYx86ilub1nNG6w=,tag:QZD8r/uL9yfGhHshTIULFQ==,type:str]
    edit-sops:
        cmds:
            - ENC[AES256_GCM,data:JdCPgZTLoT44eTIqmnJobgtM,iv:DMYmZedYlqasyAw8kDjNIf189HXgt/kJAfU9PCHMx0A=,tag:6WYh21R+Su8AkcIDYIHfEA==,type:str]
            - ENC[AES256_GCM,data:6s7ENhCUBXRUaAhjNGyg+E7jDHk=,iv:Wnhc6Y0Em8EVI+hPqrRYKy6Cf1lgqDL9P6vFzfy80yc=,tag:9hgHnkFkDy5xhZOnZIBG6g==,type:str]
    edit-sops-config:
        cmds:
            - ENC[AES256_GCM,data:RYVcc04JxQlkdoQO8PBipxfk6d4vAh+ge1YZRYJnmokH,iv:YJVkX6dAz4zpCNvUAefcOJ4f83IWeTAJzVreIP417CQ=,tag:aOmk1UI14Q2hwOIaZRYZEQ==,type:str]
    edit-home-manager:
        cmds:
            - ENC[AES256_GCM,data:ACwgeNBfJh/3SKNuXw6mbUEDYcm+zyi/z0lp2qXjFIVP,iv:x+IQBBJxN6kiaDsPfW9uC3ynxPuZJmhEmW5XXrazLWk=,tag:N/xawjon4PS/5BolY8ll5w==,type:str]
    edit-shell-config:
        cmds:
            - ENC[AES256_GCM,data:couNmrldxgeglXpVGP8wvl4hlGzGtTwzVCGPAudERqlclOpKX6FzhtT6,iv:TSInAMnnuXec4j8YzaBUmiHFtRqAJIuuzBj88ApQaN4=,tag:V4pefMNHlr2hnej1Spt0jw==,type:str]
    git-quick-push:
        cmds:
            - ENC[AES256_GCM,data:mgJb8IZMNUp5u8yoK5RFQxI=,iv:SY3d/P9B60roz3rOVM8SCbZ3K/DQUuPCsNtefIH4YHU=,tag:Qfb2ELUmrP9lOV2+FaS2Yw==,type:str]
            - ENC[AES256_GCM,data:n7ZTfsz7BOLR,iv:DmGDEf02hgC58z0SjOd8AwSb6nGau5A+rc4adhSIkJY=,tag:Tfe39DPObtgmH5jneNs6tg==,type:str]
            - ENC[AES256_GCM,data:fLw3U+8jDjYrDzrRdmaY21n/crJkbuJE7bXS4z7fk9f6Iap88IzThA==,iv:Cywl1Of/5XnsBEUucr55S7iOrKDP1NyR24QuPX1VTdw=,tag:D4muK/d2V+T/aGrCWrpCkw==,type:str]
            - ENC[AES256_GCM,data:/nJV++LegKdhn4M=,iv:dDhDj10tAc1HyIdBlK2DcTSOoQT5hipmhhGq/UqWNyI=,tag:O7y/plVpAVTHGrS+G/qo4A==,type:str]
            - ENC[AES256_GCM,data:wzfgJFoaSIaKENDnEQ==,iv:7JNXuBHZMMmnElllEAOPcIMuycSG1ei1Wf3KCm74lRA=,tag:UZivCgg8MMn3U3hkFjg1/Q==,type:str]
    git-quick-pull:
        cmds:
            - ENC[AES256_GCM,data:aPBABuMkD3E=,iv:t3ZGYntz7QoXZR5g139ZIElTNDfqbziUMpysDJUyihE=,tag:lfhiIwdZv2GQ30ISP9GXkQ==,type:str]
            - ENC[AES256_GCM,data:Rcx214jvIFajIgt3fnv+KA4=,iv:vAgQd2ro8q1CsVgTKtKmGKth2hYCtxjqKmpwksm3JRo=,tag:osXUo2+qzPjTS+HNTgxiPA==,type:str]
            - ENC[AES256_GCM,data:SRbZ08FXcrVfSOn+YQ==,iv:rmQba6G2WsNjDY1Pl3KcGchyPmUm2jVuVrgaZKrjsTo=,tag:Txf81jF8qW8FfGpkegc2HQ==,type:str]
    update:
        cmds:
            - ENC[AES256_GCM,data:PAVRBBk0RWLPUo5sIqC/2wDHHg1lu8h1SNLrRVTWDhq3zra1U0G69v+ey/B9eBdfWq/n7Ba0syg=,iv:8p1XGDVjjfT8hx7n6Y55PlHB9MEC33rDedRXZtp85vE=,tag:9UVTJNOuVLEqPEwf4MKKkw==,type:str]
    update-flake:
        cmds:
            - ENC[AES256_GCM,data:72i4jyWFKB23tq7voCkydw==,iv:YCzcvFa0wSv4c6BUQ43AN5YcUPyZ7RSv4OrffEVZBhE=,tag:ZzEDZq7bOXdNWUzyQ1NdsA==,type:str]
    updatekeys-sops:
        cmds:
            - ENC[AES256_GCM,data:WuFj75Us2nMek67zf4eInjflBHAE2SjpyKlOjQzgiFmy792Zbp+mITX+920Z,iv:b983wEZCSyl7TSNclWridb+k8VVJEgDrqM/F5T30tn4=,tag:Rq4kyrXwIEqEFOC5QzJgPg==,type:str]
    exit:
        cmds:
            - ENC[AES256_GCM,data:cdhg0Q==,iv:DoOPcF7u5nXIGp3mDC8iBXQODcaeGpw6Mmlxiqm2Nko=,tag:XBYoxdozxAqaSXLCGQkRrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tsv2lurpjzyx9ng6hcc4dff23lvv7tqkyyxz5zlpx32egu2c9vfql9m008
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NG0yUXJYSzVmZDA1V1Ni
            Sng4dE1hTjJHbjdxWG4wOFAxSTJBaU1xUVc0CllaTUJ5V08xVzlkaGV0VGo4eWFV
            aGVYSmxMN2grcGhZQnQ4dHlkTTFyTkkKLS0tIFNOekZJTWpUQlNKdlMzeWNQcjNv
            dEhPVkRJNzBkclQ2TytRZGUwbzYvemsKrQA253xaPNX9dqVlWmisjBvd7c4avLgy
            lksgjZZ8+Z5+fWYK6SI235JLdY9ApPGNNBgOnWpKaJMnZ/KymyWhnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywan3hwg4v306e3gk4sjzfvjfxru432kgr3xlmwu77nkhgsjmfuqr7lktd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRUpCWDlMQmxRdFpQcVdZ
            aDVDNXlxdjBuUFYvSUNwTnhLMVlZc01DUnowClpFU25YK05ka3FId05zN2lKOGhG
            dEhTMHVvRkN2b05uckRsMmdoWFhlaUkKLS0tIDFOaDBxWmE3VEhWRlgrUTV1amRw
            ZHhaWWV0ZUhpWXh5UHFFV01xaCtrMjQK37RO5BHSonfYz1wahIfg2nGO3HOd8yE4
            H5HyFgrmyvNVPwCdZlbSbxd0VNo69v7MRDrVWMdesk22DNPziKVzfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15ptau7jyv6kcwz39vcfzxpw95p97l5r7uywkcl5g83gqxuhh7q4saggagy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRU5Pc2VPUy9tbVRsaW9l
            bElacjdRQXg2QUtzM2R0UnI0SE1yRWVZYjIwCmZheE42VXhoQTNMMlo5QlZ0ZUpD
            K3pjaFVqaVdkL29YSFBmQnlrbHI0Q3MKLS0tIEVPWUUzZk1Uc0lEclJQY3JkTUoz
            cmNmWllNc0ZIdmpaSlk5N2Zqemw2TmcKzOhBv7AJRByC+fUG8W5NYO5/vxHUVXj2
            uC740SOPK22oeIdK4+t6qQc4EZ7hoo/csjN3CfYQD52r1SBxkP4pwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezs5s0mx7pcmv0cq6lhvxqtrgx9shrenpxuqyny3m52rg4a6vuxq9ucd7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVGJaaE52ZExsaWlDR2ZG
            dnllK3p3dGV1SnkrMXZzazFFSjF5ZFZKa3pFCno1WldmcXduZzBFVUlxYStYWTh0
            THZtb0VGVDdoczdsb0h3ajVLVHlmUWcKLS0tIGRSa284YTlERlZZSXJvM0ZSSkVL
            VXljc0RqTTc2aUUzMDN1ZmJ1MFdLd0kKCDkjtpyDtI1ipUcd4qSLsCOWYu/YsZr9
            KX9ZS3j2UHM1sZ9wuuZ9Oam9Hw9RXrNlloeTIyXTx71zsTfl4rZs8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10gx43rew42f7a2t0k4rgqz82yw8txym0p0wyrely3gwlavrlpe5snnjrln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR1BvdmozbCtlTG9Nbk9k
            ZTRGbDB1bkJKak5TcUUvWUFtSk1ZdjJFT3l3CnJRWS9lbkdxSmxvQktjZWdYdGJT
            eFdjVHdPblZMV1VjT0xiN202TTg3RDgKLS0tIGJtWFUreC9lRnBLc3VmczQ3NkI4
            OGhJRm42emV0M2tHTjNEQVFBYkRGV2cKiO+7ssZRtP80vlXwWiTmlM6Nw8+kOmWp
            ZYsDQ0Nlm8u55GG6TH6ZbvKYppdn9j1NBn2USyyfbab0qJpeMoRw7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12yhcg6c7spluq7z0dsgduqfvvcqzyz0a5an3zsndecuc0h2w3ftseyzlad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ1dFZDJ1Q3d4YkFFTWsw
            R2l4dGV2Ymx1d3ZvdlAzV1VRa0llazJrcjJNCmh3WEJSV2RldFRFYTVpYW5pVy9x
            QlY1VEQzanZpTnNqU0RYRmZHWGltQ3cKLS0tIGR5SzN6a1ozdVRFcTNkREFHVFhS
            bGpubjNacEo0anJtR3FiVk9Qb1hVMFUKYstlFYSLUFstQZPgNGxXyqv4p/kwkSgu
            wUKria1e+ymiylj4iV/lnANByY0N4EpMQaskwQLXzB1EfOFpQhRWAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cpkcemzhdkc5zmghdx63qv0km2t934raj6fs0ff7uftet00fh3qqjc8wq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ3k0b3VzRzRuYk13WVRB
            WE16cnNyQlFkVjRuTTI4cEpoaWFnY0R4TjAwCmdEaU9oVWt2SUhXQk9CNURtTzFw
            M0JuOWVqLzBTTXk1aC9PRUtsaGNzY3cKLS0tIExkZTRvWXpGSzIzMUMrQVVLTjZ3
            YVZkSCt6UTd2SEJRNXRlT2puQk9SMlUKSULxzjeC3LvS2EqVDwTk/ApfJWOhCsmX
            Ux6Rd7OxdRLWmKPJeMp8SMeDgCLWiJZC0jfm01Qr1ln/c9Wqf+k9nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T08:48:03Z"
    mac: ENC[AES256_GCM,data:dpr5TJyeL/I/ZhCldFXKbFjDAfishXUfisreEWxLpcgNlCaIGoKKzrJQfxVFo/LmVOhtezMWNGFhoUCJaG8tZELyB3w8eFnIvcKgc1YLyoh6CvKN0y1X+6SG0IoTLGQMEU7iFF6qm8lOCSqZyVaIS5X5ELXzHd65YdNiRAbbcYU=,iv:ma38XF7GWhqPkrZlDZAGW0uPr+itQFK/uoChE3Aro68=,tag:3jNi9evMHJ1J6KjpOlqcFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
