version: ENC[AES256_GCM,data:Wg==,iv:AkAQEQlnW2ucgqlB64naB1aCWG4HqdhwIGv3DjOnhAE=,tag:7nNBikC1/oiU3PnmacyTZg==,type:str]
vars:
    GREETING: ENC[AES256_GCM,data:vSUkpGsgygXRkh11og==,iv:gG8Rria1+jHVjwFzmnnRwzmW6R4e9BKZYP/mpCccyos=,tag:cT5+4RCCP24sWD8i1DGIlg==,type:str]
menu:
    - ENC[AES256_GCM,data:r5D+PVzzCw==,iv:q9ayGaS3u2fVHtSloLeu517ma88w6CVUYhHrByMEWtY=,tag:EfWUFWTqdtPawR29Xr537A==,type:str]
    - ENC[AES256_GCM,data:lBUQwg==,iv:Pz/2HMtfeM4roAAQ1AkKjuJN4dLCD4YRTYFOmwaScsc=,tag:Mewllgrha7knCZeCBOZZGA==,type:str]
    - ENC[AES256_GCM,data:LMFbqlKO,iv:4bPY4k1M/Bu7ShSv8nUqOdouKHQqEa9VT6PxTi67G/s=,tag:XGlnSua88Gk4CSaYJOtC/A==,type:str]
    - ENC[AES256_GCM,data:B4TDOMQ/WnW+314=,iv:GvoR+N8LLFah0oQz1LrZKC+UL0lQIS7n09XoPzLY0To=,tag:h+t3q9jOqwwXkCb/tSqtDw==,type:str]
    - ENC[AES256_GCM,data:RU49X+fOY68cGZ3CE1E=,iv:IDm/07RC66aO35GRqGvtw9y05OAk9Vr2WKdCM4WsT/c=,tag:7dFbLt5BctnOIAA+ETnUGQ==,type:str]
    - ENC[AES256_GCM,data:F/0hWrRN,iv:wWOpQ3gfXC5SjfX7BuH9lrfw9V3Uls4aWezQn5wacwI=,tag:G7wtT2T4RdEXFTZQSm+CHg==,type:str]
    - ENC[AES256_GCM,data:BfqjGg==,iv:vAMn52DvLXzANxbVFA5g3HmRBwrZyXOjRYpAeZUw74Y=,tag:qQgRmZbG7gPCf5iHxDtJfQ==,type:str]
load:
    - ENC[AES256_GCM,data:e3+BLrHFIFCX,iv:+qwnQkW9cMDPkWDmV7XysOvro8HTV2mYff5aM36lhoA=,tag:K7tS0Li4fKBwxl4fWzDKmQ==,type:str]
    - ENC[AES256_GCM,data:Um61nC3HGQ==,iv:krK+Mgm848jXnNPYj5UQHc4kuysMzIMfICwFV45Peoc=,tag:TvFGeaHWL1tpZDOQHlzsOg==,type:str]
    - ENC[AES256_GCM,data:UnqRxg==,iv:EvC25+n6ySo0B89FzTKvgkWF3mebBsbq3BhG+1Tz94I=,tag:ceyMhbarQRXcGfNPu/gqTQ==,type:str]
rebuild:
    - ENC[AES256_GCM,data:YDDqxNVdoHUb9RJnHg==,iv:ZK2DN/WokTdhelxVrlrWsWoOB5FuZEJfaOUzoM0ekx8=,tag:hnm2ekWKbLxQqFOUH44EKA==,type:str]
    - ENC[AES256_GCM,data:Yimeo+UYw1l0FY6Ef1I=,iv:FZDO2oLGhfcHG85UomzscIY3i7CZHwydn61xfYo9cvo=,tag:cxZbbzF0yKqwTJgSFubqbQ==,type:str]
    - ENC[AES256_GCM,data:RKGGfSTeGPgcICgzgockBRf2fak=,iv:glTgp1WWkA/0H3iiPcS3WcAPV1oc8XA+m3cm4wEbK2A=,tag:I7/eEXa9YhO0rf4lGg+6iA==,type:str]
    - ENC[AES256_GCM,data:rPtmDw==,iv:OSRfttdwW6KNLvUo53C13eQ7NseZTBMkR0xGZWjhDw4=,tag:4NvBzUJLL5M/DClHvMTTRA==,type:str]
browse:
    - ENC[AES256_GCM,data:3xQ0xp6qVJJaXU91,iv:nNnavemlY58zd9/FAfXXKtsQqhFKBgYjNE86ODeNuP8=,tag:Se25FRXqsJovKzBjC7Qz1Q==,type:str]
    - ENC[AES256_GCM,data:M8W1WmMtR0eNUTVm+mj5,iv:QfLmfdhbXhWe/UN55QKD8xBSJgyuN1N12+DSPuosZp8=,tag:tjyW7BbMtJyRXlkHSbJKRQ==,type:str]
    - ENC[AES256_GCM,data:trs+rc2bpWU=,iv:6vYQ2fCExPXyniw93SbwAp8pdC5XeoDnMzRQQL8uJLQ=,tag:8U4/7W1iWoVX+slDJE9PRA==,type:str]
    - ENC[AES256_GCM,data:wSZ55w==,iv:g+q6DHNpaQg0YHGmXwxypQYslI/CfzBQry/VS8gUCe0=,tag:p0lrxVKPyoLRv6WGxzOX7Q==,type:str]
edit-config:
    - ENC[AES256_GCM,data:hwDx+YQl0/AtW9FOng==,iv:Mi0GhzORJzo39+49fjMskXui6lnqZJRN0XGX+/gnr84=,tag:SPbKmTFs84y3/E/lJzV8hg==,type:str]
    - ENC[AES256_GCM,data:WEfcmocy8kvok50=,iv:sWuxSZBKIJ4SXqRzHcHR9QLfWAwWRF5fsX2eSEapvuw=,tag:iOSMnmc/iKvKiqui863UnA==,type:str]
    - ENC[AES256_GCM,data:DlNdKpo1hqnVA1gi,iv:B0enaeJSLaeJksKV6MypQE0eFsLNhB70rpEVYRUtvfM=,tag:uTKdQKHWze2Ip1v3uw54oQ==,type:str]
    - ENC[AES256_GCM,data:en2cz80EbVR/,iv:tU2QvJewXACt0tfs5VyDH5jXLShZcuRmezMucWokhUE=,tag:dlsz4jozBzfs0Y9LCOWooA==,type:str]
    - ENC[AES256_GCM,data:oo/0oaWlPoQPj265TVYjwQ==,iv:TFXvO7bssS2Rfz88JfDjtRzNdpJLGRAi4+qN+b0LH2Y=,tag:Xj8tkhpuU7Rot1UTJ4hVjg==,type:str]
    - ENC[AES256_GCM,data:7RN2+8Tf/acVY2MrB1MxM9s=,iv:nrC4ljp/meBp74SlXUt5BY4usWD+fP+jlv3G+uk2T5g=,tag:/VPI0UQsFsABZjpRpIhaAg==,type:str]
    - ENC[AES256_GCM,data:0ki+JFr5JnOVwDLYucYY1EM=,iv:pYtmN52/0ZX+3iddhP7uHsLZP5LAr7oE6cUnoKULqls=,tag:EYXFD85a+MLca9Wxx24G3g==,type:str]
    - ENC[AES256_GCM,data:c2pF+Q==,iv:znWJ3zQeGaZyFRXO1Hb9Hn0wfnyeHShPFcuhYGamOuQ=,tag:msF3bP6wyPUdL7Tyl2m9UQ==,type:str]
update:
    - ENC[AES256_GCM,data:MSpN1eAUFLOTQXb9,iv:nmOiviJ0FXvJQkVj0cULI9F/ZTth77AIqQkemp3AMhM=,tag:2aR3Xbk+7AnBpoDWVkRNkg==,type:str]
    - ENC[AES256_GCM,data:hF11Qr8mWj+Dei4=,iv:ZbXo9iwmVjpkIKSP26ih42x/Nd7j6pNrRUWJa9kxFg8=,tag:cklTleawG3bDixLaFYJy1g==,type:str]
    - ENC[AES256_GCM,data:B3fRCg==,iv:jxoNuwKPnaXSUDTbG7tVOhZDmXSbkzh7rv7r2E7+CH4=,tag:+151YV8/VClrAPIZkqkdYA==,type:str]
tasks:
    default:
        cmds:
            - ENC[AES256_GCM,data:UL0NUBScXO998XL91IIEMM72zxp1Ww2mWDfvnYg6U1jc1+NSVUpX9OAWfXp5aEMu+RSpa4ss,iv:MOz/2wtz6WrzkTTzib5k3Au+z51+F5eku7gxoLtuSrY=,tag:IatpMObfus900eT59BIO3Q==,type:str]
        silent: ENC[AES256_GCM,data:peo3mA==,iv:rF178fkyiKK0q6vD2Uq/7FAeFazJQqD1FjLUqB2gnmA=,tag:u03pa69t+4qDoGcBG6eNvg==,type:bool]
    rebuild:
        cmds:
            - ENC[AES256_GCM,data:O2hWjbEM17Y9hp4mRFU6hB5s8hLlXb6y/5Vygbx8URy+bX1IdriwQy7iUsfd5LaVf2S+jG/P77oz,iv:+l73atuntQeKfu0gaS6p/6eywlmlaKA8GpiQq0IbWY0=,tag:tRVvZVZrhtPGzq5TmteurA==,type:str]
    nixos-rebuild:
        cmds:
            - ENC[AES256_GCM,data:sEP1UDxII4oC+OmqEaYJvzhu67Uvo7Ondhi2d+XPQWYqpoebqWXAeevMNdDhu0RzAWgRlxt3+oLVLNTQPIS/,iv:w6KLxQzD4nR5XTCZmKXOsGTh9DnbFQWyLTeMm4dyjFU=,tag:Y4lGmdKG1GE70O/eUOEf5A==,type:str]
            - ENC[AES256_GCM,data:vaHNIxMHvbLw0HWMIA==,iv:3sR2LnHBySj2xeZCL7ypJ3FbfFyasrNuFipEDFQdjNs=,tag:qVWhiq5Koe/qVLGKwUQzjA==,type:str]
    darwin-rebuild:
        cmds:
            - ENC[AES256_GCM,data:OmdA0ELLctmwwWsKeU1bUBHDrg7vdPJmKl2glx+IoIIRDUfjoISLRlPoTYQi/CZAzhxRq9W/W11e78A=,iv:SwTt07vJEKaYqUzDvfw4qVQiz0dvueADkU3BsO7jfMg=,tag:9bmMOxPbRyRne8DxTibavA==,type:str]
            - ENC[AES256_GCM,data:4YXrzg1g77D7UzqaUQ==,iv:Tw63OdHjPYd8Ts+Emwl/nVnP2qB80Zp8h0UEJE73PSo=,tag:xBWm/2cTJQ9O+hKlllOt5Q==,type:str]
    home-manager-rebuild:
        cmds:
            - ENC[AES256_GCM,data:EZ0P+MYfg7OCqzk4cb6RHDvVhKDHA9ER9FklqezGUG6H2TlX9lqsFqlw9PykU2EqJok7ohbr2kiZVvQ1ow==,iv:VOs6HxdYOqukUm7BBazBnsTPdZuUAm0TQAcZICQtum8=,tag:d/tJRHUccc4ZXUs0LavsuA==,type:str]
            - ENC[AES256_GCM,data:9p+kLQSHm1K9f8Ob4A==,iv:JA5eUT2CynB4iGeB1/8PuCbPRgRsmzm7QhgcxbBgrz0=,tag:JMDwx9S+5rxnTmAMBlS0RA==,type:str]
    load:
        cmds:
            - ENC[AES256_GCM,data:/ubzVfdMd8sQCjSogb0bOMB91Phj5ptkYR2BKtr3mj9ilDoNsbQ4pZgx39S0dcMd+QlQ9Qhw,iv:+LAH+OKLnGeB7bg4cHfqwc5iS5X+AX+gQQ+nw98U+4U=,tag:aVuMxE4es/2LXy2cKNQJ0A==,type:str]
    load-groq:
        cmds:
            - ENC[AES256_GCM,data:nwUEYnCc8TPodsFTRJJnSoAN8fjyokH7b0DMtYfiz0ARoYlcI3KAhx642jTMKguH1OodpvXAF+S7SXuOvvU9lSdLP9ltvqBbsRjOQ+G81Jk1MlyuHVFiT7PL8A3mJMITOugJAg4VvaFr54VchQCDSTCN9rK1u5giQTp6VhDf,iv:UtOHpKjHI/antVACw7bUYqqXFHENWH5tPWRa7lQn+Y4=,tag:2JsmjQH0zdgi0K27k86O3g==,type:str]
            - ENC[AES256_GCM,data:p93BjgTUOesjJHXCS1rsxNhPze7RWEDc0eNpYRt6KofB0yoj8GuVl3jTcrnoSmlIp03hs5Njgo89LJJLc/V/2czSNtguYLprsXpaf6JPIaByoqO1Af3kPyyDReVvah+gtGxb/PdRVYZHZIiOUIp7CpgX+sw0H5d62lWGzqTfP1CLMUhm,iv:+GhW7dqGwh7EJ6QW/jSP0u87/GnWNO2LkYT06wW9GY0=,tag:FhKhg/+OlpdBM9b7bvpE+A==,type:str]
            - ENC[AES256_GCM,data:5rWWQF4QeViG5yhsLQns,iv:Mtb1Qkaa/qLu5PS8U9ta8L0UqepyQM9z2VDAN71fSI4=,tag:0dkIztilYGypxme3yeaBxA==,type:str]
            - ENC[AES256_GCM,data:brbciilEImoymRU=,iv:sXfzCHII4XeCT28EZPdeti/45pMVE4X3bnzDwz4GLJs=,tag:AZxaXJV8gTJJUx5eAJz6TQ==,type:str]
    nwmount:
        cmds:
            - ENC[AES256_GCM,data:xTpVaipp9yS465sJaIQPklDLE8Yh0csS+INQ3bqi6lohaOpzMVb3J1mX9Kb15dunbYYsV5GwKSp0v+SZUU0AGW8LgQY4aDxfQsjdECk2Np4iQqMta41U2zyrL/uNdz0SXzCjA2IE,iv:aMaw1cVDQFVqlp0tmvf7JSQgVQbVWjqomhtPX14XiIc=,tag:3+aD4HKHaWwf3dj33URTNA==,type:str]
            - ENC[AES256_GCM,data:/0W1tZfjzJ4ZoA4F5UX8ja8aG10qZwhXWmHIkcnQmth34kOw+cI5O9XTtLl5MwHnTAE3KevfasPiIs6OlqkrcMikttB9joxZE7QPzzTjfmUSlX0tM/P3zdJgRCOLNdLhVJvB0FXu2/368Q2MdvQi+BPRaQ==,iv:i2diudOOL5Of9zjivFaHGT8dAaXW5rDdTS/z+lHwbqg=,tag:riDoBbO/1zDyUVEqANkTGw==,type:str]
            - ENC[AES256_GCM,data:7jJOaHcbHV1idaK3Zrm1q8GCHPlMUo0e3v8lTDanN/9mFB/w7WYeUM0BKZkVMi2mI8TDQTQ78ssP1tg6U3xqx8MfWFdYDc6hJIDL+nV6Drp4xf5EJmRuIwHxjWDKOnu11GMx2Ai+sDyAOOlvp91IseTOAdYItYkSrg==,iv:IlB4/W4pU6VNNw5f4vs+cFhibW+T5tASjX9kgJE3YOs=,tag:wLvAUgROI6mJXk725p98PA==,type:str]
    browse:
        cmds:
            - ENC[AES256_GCM,data:abns0B7JEaZRuRuNq/HUgPPj+yc2qwhKzw4lfjXjnu09QoqT7QhYWaS9+SGXyyymLhEgs3Jyfhs=,iv:6S6zjrOsiBb3kJZEqxrduLPezcN0IKrHp1E19YXfkfg=,tag:nOnAk4+07VktJwYPVPrnHg==,type:str]
    browse-notes:
        cmds:
            - ENC[AES256_GCM,data:DT/ALFVHWdkmCOl2f0fOrSKrPsrqq5eQTabgqb7uZjcnuh+3A/RuBz5gwXMQM9Cbd/k=,iv:+D/n5m1okma14QM70pNgYCiBF5qE90ghXzED50W8+jg=,tag:D2Emczeo92ndrIE3nykPIg==,type:str]
    browse-internet:
        cmds:
            - ENC[AES256_GCM,data:KUyqTWS5JIhBbcTfjzwVDPkxKw/3oWE3Lkli,iv:etboXBDRxdNhLX/f/iv8Z3atpHliduxDbU5HYtIG7Ac=,tag:/EFIVZ48h48peJPZFGA2IA==,type:str]
    browse-projects:
        cmds:
            - ENC[AES256_GCM,data:45/OdGHRQdzs7VnuqbGlTEt7Y/g3Y1CK02DJjqxJvu4=,iv:bB4h71GEE/yb+I7R5kqvZqu81aAyZucLpLl3ykEeWFQ=,tag:93VYxFmC9/JvI3FcVxg/KQ==,type:str]
    edit-config:
        cmds:
            - ENC[AES256_GCM,data:b/ja0sxTSVlAJFuEhdZ2CJMHG2QUHxPxOQAhFhyxhHpf8N9l6RpdT1RXRXqNzvvQeAfDk8KqC28WH++wbQ==,iv:NmGBlKU4G59sKgMdNXyw4HYYpiU+iPB+lzYFFKhoBIg=,tag:Qh3i9golUy020jNqwoPbOQ==,type:str]
    edit-taskfile:
        cmds:
            - ENC[AES256_GCM,data:AE5M1m8WTjAzX+J+uX6zVIPEm0ukhKBRGlgqwFPBX7zMe6hZm7szsZi7uhcLIRX7,iv:EF3pd6lyv+DEWOrLl3ojeTEJcibKQUQ2UQ0xj+SOvVg=,tag:bNJtei01IXQKZBFb6w2omQ==,type:str]
            - ENC[AES256_GCM,data:DV+ke9N/ctA3HhcUspSTPm/8u4cInSAFRaeRYa/2pWvzbZGiT+5n1SrjOS/pGg==,iv:1K9ErFaR8BwsJeu0+qri5Mxw4qGfYAnAx06NpQp8Dt0=,tag:kys4BSvn3X9JbASJQ6OJzg==,type:str]
            - ENC[AES256_GCM,data:isl4mCv5BYIMF28SamP/21SkPkiamb2uRR1uL7o8p44=,iv:cAMO6wXYWFdfITU8tRn5mHsvqlnS4sVDHoELTlW5V+A=,tag:vJ8fVil/cWZGobNMc8ViaQ==,type:str]
            - ENC[AES256_GCM,data:g9B9Ok/tJ5ro2Qo=,iv:tDSeg1WmZEEwtPkB43pmTabT6BMkEnQUpYm1MMVjY7Y=,tag:D87khWqgXx62O7bX2GOHYw==,type:str]
            - ENC[AES256_GCM,data:DuZ+m09FLXIQQH3PBg==,iv:KX0CCAnAtlmtPg1N7N05mc5NZJEAH0jraV6aEsJJ8Cs=,tag:MXxq0Q/2XZXaaYbnoHRLtA==,type:str]
    edit-global:
        cmds:
            - ENC[AES256_GCM,data:A/Lt2lZJyMYUFBbYsfeC8fKlsdQ2kpPN2HWAnnKH3C+gB78=,iv:x13lpcajIZnDiMrlRAvFwLJHXNZxSakYuR7DXFTxsgo=,tag:23YIeSc8MbdytLximoxFtw==,type:str]
    edit-secrets:
        cmds:
            - ENC[AES256_GCM,data:jAR5bbulX/SOe7TzTP8w6kRIkT2cW8b67YcOYCl75hL+q/84T4encgfCNQsq7jg=,iv:zhnlfuy0WM8h1odJ+/w1bhgi4VBeJDwVbb6UI/qnEGc=,tag:40pqicFF03mFBwVNyROQ6w==,type:str]
            - ENC[AES256_GCM,data:emlEkAQ3yLyKzR8yKO4c524kohmp3epAUm+BR7KrxWO+0/+Hja+PGaf3AyuZ,iv:6jEuO7re0eEp21/abxAx9+cc0GJBlzyY8vRFAj0cw8U=,tag:VO2ylrjOCpm7hJhpcI1A1g==,type:str]
            - ENC[AES256_GCM,data:iGDmClCjqTwQfEXDzYpijGcFldkMzzGtH8dVHkoV0Q==,iv:Uupqg63u8e74C6Kh0yNTYaiLleICtNqU86XJxFWzrHA=,tag:5UL/oyx7QIv3stU7gWAmFg==,type:str]
            - ENC[AES256_GCM,data:E8kS18Jqdn+3yM0=,iv:XFfdi7HhpRbrOvfSntirsE7ZOlqjAYx86ilub1nNG6w=,tag:QZD8r/uL9yfGhHshTIULFQ==,type:str]
    edit-sops:
        cmds:
            - ENC[AES256_GCM,data:JdCPgZTLoT44eTIqmnJobgtM,iv:DMYmZedYlqasyAw8kDjNIf189HXgt/kJAfU9PCHMx0A=,tag:6WYh21R+Su8AkcIDYIHfEA==,type:str]
            - ENC[AES256_GCM,data:6s7ENhCUBXRUaAhjNGyg+E7jDHk=,iv:Wnhc6Y0Em8EVI+hPqrRYKy6Cf1lgqDL9P6vFzfy80yc=,tag:9hgHnkFkDy5xhZOnZIBG6g==,type:str]
    edit-sops-config:
        cmds:
            - ENC[AES256_GCM,data:RYVcc04JxQlkdoQO8PBipxfk6d4vAh+ge1YZRYJnmokH,iv:YJVkX6dAz4zpCNvUAefcOJ4f83IWeTAJzVreIP417CQ=,tag:aOmk1UI14Q2hwOIaZRYZEQ==,type:str]
    edit-home-manager:
        cmds:
            - ENC[AES256_GCM,data:ACwgeNBfJh/3SKNuXw6mbUEDYcm+zyi/z0lp2qXjFIVP,iv:x+IQBBJxN6kiaDsPfW9uC3ynxPuZJmhEmW5XXrazLWk=,tag:N/xawjon4PS/5BolY8ll5w==,type:str]
    edit-shell-config:
        cmds:
            - ENC[AES256_GCM,data:couNmrldxgeglXpVGP8wvl4hlGzGtTwzVCGPAudERqlclOpKX6FzhtT6,iv:TSInAMnnuXec4j8YzaBUmiHFtRqAJIuuzBj88ApQaN4=,tag:V4pefMNHlr2hnej1Spt0jw==,type:str]
    git-quick-push:
        cmds:
            - ENC[AES256_GCM,data:mgJb8IZMNUp5u8yoK5RFQxI=,iv:SY3d/P9B60roz3rOVM8SCbZ3K/DQUuPCsNtefIH4YHU=,tag:Qfb2ELUmrP9lOV2+FaS2Yw==,type:str]
            - ENC[AES256_GCM,data:n7ZTfsz7BOLR,iv:DmGDEf02hgC58z0SjOd8AwSb6nGau5A+rc4adhSIkJY=,tag:Tfe39DPObtgmH5jneNs6tg==,type:str]
            - ENC[AES256_GCM,data:fLw3U+8jDjYrDzrRdmaY21n/crJkbuJE7bXS4z7fk9f6Iap88IzThA==,iv:Cywl1Of/5XnsBEUucr55S7iOrKDP1NyR24QuPX1VTdw=,tag:D4muK/d2V+T/aGrCWrpCkw==,type:str]
            - ENC[AES256_GCM,data:/nJV++LegKdhn4M=,iv:dDhDj10tAc1HyIdBlK2DcTSOoQT5hipmhhGq/UqWNyI=,tag:O7y/plVpAVTHGrS+G/qo4A==,type:str]
            - ENC[AES256_GCM,data:wzfgJFoaSIaKENDnEQ==,iv:7JNXuBHZMMmnElllEAOPcIMuycSG1ei1Wf3KCm74lRA=,tag:UZivCgg8MMn3U3hkFjg1/Q==,type:str]
    git-quick-pull:
        cmds:
            - ENC[AES256_GCM,data:aPBABuMkD3E=,iv:t3ZGYntz7QoXZR5g139ZIElTNDfqbziUMpysDJUyihE=,tag:lfhiIwdZv2GQ30ISP9GXkQ==,type:str]
            - ENC[AES256_GCM,data:Rcx214jvIFajIgt3fnv+KA4=,iv:vAgQd2ro8q1CsVgTKtKmGKth2hYCtxjqKmpwksm3JRo=,tag:osXUo2+qzPjTS+HNTgxiPA==,type:str]
            - ENC[AES256_GCM,data:SRbZ08FXcrVfSOn+YQ==,iv:rmQba6G2WsNjDY1Pl3KcGchyPmUm2jVuVrgaZKrjsTo=,tag:Txf81jF8qW8FfGpkegc2HQ==,type:str]
    update:
        cmds:
            - ENC[AES256_GCM,data:PAVRBBk0RWLPUo5sIqC/2wDHHg1lu8h1SNLrRVTWDhq3zra1U0G69v+ey/B9eBdfWq/n7Ba0syg=,iv:8p1XGDVjjfT8hx7n6Y55PlHB9MEC33rDedRXZtp85vE=,tag:9UVTJNOuVLEqPEwf4MKKkw==,type:str]
    update-flake:
        cmds:
            - ENC[AES256_GCM,data:72i4jyWFKB23tq7voCkydw==,iv:YCzcvFa0wSv4c6BUQ43AN5YcUPyZ7RSv4OrffEVZBhE=,tag:ZzEDZq7bOXdNWUzyQ1NdsA==,type:str]
    updatekeys-sops:
        cmds:
            - ENC[AES256_GCM,data:WuFj75Us2nMek67zf4eInjflBHAE2SjpyKlOjQzgiFmy792Zbp+mITX+920Z,iv:b983wEZCSyl7TSNclWridb+k8VVJEgDrqM/F5T30tn4=,tag:Rq4kyrXwIEqEFOC5QzJgPg==,type:str]
    exit:
        cmds:
            - ENC[AES256_GCM,data:cdhg0Q==,iv:DoOPcF7u5nXIGp3mDC8iBXQODcaeGpw6Mmlxiqm2Nko=,tag:XBYoxdozxAqaSXLCGQkRrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tsv2lurpjzyx9ng6hcc4dff23lvv7tqkyyxz5zlpx32egu2c9vfql9m008
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZWt4NEZlQmdSNEtRKy9C
            UUdERXRCdFlOUTlsRVllLzNDNkhVK1FDRWh3CjdhS1lhYzdNSjZsdTZEeW1QTm5t
            bmw2dWx3RTFwcXBnMXlCWGU0OUF4YzQKLS0tIGxzYUF6WXdMMFcxY0l6aUllM0Ey
            c1AwZkRVV2NUYWtaYU5iTFRkRFo1a0UKYceJDQeeU/2PZoCP16LKXx8DWhzg0+Go
            9ts6cSQP1KnMrRKiWemufgyhRnnMWDwFLsz5QP+ah3P28JNKLeMyAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywan3hwg4v306e3gk4sjzfvjfxru432kgr3xlmwu77nkhgsjmfuqr7lktd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVk5qMk5FZ0pZQmVtditN
            RlB1SER4bHlLOUVNeGJ5dGtKQzloUXlETkNVCkJVM2hEeFBsNXdOb0JYSzcxc0NX
            d1d1cTRmV0ptS1JhWGFoakNCN1RaTjAKLS0tIFJrK1BhRXBsNU5zcUJYcHRQZEtp
            WWhaZmpVYWVqWGdKSUZ4K2V4R3BtWlkKbs7J8vj3OoxkcqJGZHSH/jLhhK5226hY
            VJZO2a2HGPvYrxz+DvvrPshMNVzq1g9ZSX1r5zvxFlJf9vKqjQw3Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15ptau7jyv6kcwz39vcfzxpw95p97l5r7uywkcl5g83gqxuhh7q4saggagy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb21paFdkT0NVWDlCODZ4
            NTlwL0FselM2dEh0eFRZRkJRUFY3ZzNqY2lRClpicGNVdUczR3R3NHJJWUtkWGth
            MmJ0eFJGMUdFL0UyR2xGcEFsMmhLRW8KLS0tIHV3Um9JMHVkSWJvd2FYNVVXbmFB
            ZUNWb0xEUThaMnovNm1ZZDNGZ0RWNUkKIv77NjHYxKpH5dQgpnIc0NVdOe9q0GYc
            Eftk+exUcxS5D2fiqnyR8h7VVSPtTbgcR6+6vcL7EYVd79VPJSx/+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezs5s0mx7pcmv0cq6lhvxqtrgx9shrenpxuqyny3m52rg4a6vuxq9ucd7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOWFLK0dGUm16a0lXMHVU
            K0wwdzVreHVlZmZOclN1N0tDRkdyOVI1VEhJCnBpRnNtOHI3cE5nZVhjckUzRGRk
            Rm80cTBoM3VVaUIrU3laWWVjZkdjNFkKLS0tIHdZb1pZZGhLNzNyN1JtWWYzQXhw
            aGtTbE50bkVHcTBkeFB4a1dvNnNqVlkKSOgiHh/xmWseGpc/KcMA2oMaLHAiPVst
            8f4lHYd1WeRPh2iIiURCo73vqORfmBTjm+k0/x08C/z27Y/Q45asuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10gx43rew42f7a2t0k4rgqz82yw8txym0p0wyrely3gwlavrlpe5snnjrln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWmRnUFgxRXlVUGhETkZs
            NmFlT2U3bnZsYTRVRGdHV2IxU3B6SnYrN1ZVCkludVEwOURlMTVsVFRZeitXS09z
            S1NkaEFzSGpveE5pUklVaXZBZ3lJVHcKLS0tIEJRWmwrNWRoRHg0L1lnYi96Vmlv
            MG42MHE3bHc5eHlhb1pQd20vWTc0Q28KQ3t77QuxzKj+g5xK15aAUPSBNrCyL3Z8
            Oy/8JPUcwiYcOmUEL/TYGuclgYyG0CYCIrcYFXVeXgShzeMjKgNMMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12yhcg6c7spluq7z0dsgduqfvvcqzyz0a5an3zsndecuc0h2w3ftseyzlad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TytuR09Yb2VaMXBNYzR5
            WmgyZTBZTWp1V0RHTC95WWR0T0lLMUtpSWc4CmFGanRMZkRPV0ZlVE56QUhjZHFm
            dHpEVmpXOU4rbnZpK2pRSFBLSG5KMEUKLS0tIDc5YXFBWk16dThOaHFGMXorN21J
            WnI2TTVOQ0hOdFZ4NDBTeTIvS3lYQkUKjS3Phzaa5TNT35hITQbIWQAKGlxYpC3i
            bcnTiwc3M5DzvMJZ4Zv2q8KHXrBp3UJKTZM3/+IRZEqgmQBB/74q4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T10:02:50Z"
    mac: ENC[AES256_GCM,data:WE5/E7guVOj+fXxWacAYUXEQ1P9rPOATJIw6l4aUPyXTFqiJcscYjqirn0ej9rhAyr8IzvyQjn1OOtKMfbXUtw758tp7X2dmnEcQcQDaAXXkgWUQ2F6l1AD60vmPg+pnCbm1heLb6AvlCM9ZmFoCjKim7dlKLQThz+KlOLjHs/g=,iv:FNGZ4iEsqkbTSwQnXcOKqtnpgQYCDcgXcHihNAsL978=,tag:RwKpVkgvaq1qkMxH2sUIhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
