version: ENC[AES256_GCM,data:Wg==,iv:AkAQEQlnW2ucgqlB64naB1aCWG4HqdhwIGv3DjOnhAE=,tag:7nNBikC1/oiU3PnmacyTZg==,type:str]
vars:
    GREETING: ENC[AES256_GCM,data:vSUkpGsgygXRkh11og==,iv:gG8Rria1+jHVjwFzmnnRwzmW6R4e9BKZYP/mpCccyos=,tag:cT5+4RCCP24sWD8i1DGIlg==,type:str]
menu:
    - ENC[AES256_GCM,data:r5D+PVzzCw==,iv:q9ayGaS3u2fVHtSloLeu517ma88w6CVUYhHrByMEWtY=,tag:EfWUFWTqdtPawR29Xr537A==,type:str]
    - ENC[AES256_GCM,data:lBUQwg==,iv:Pz/2HMtfeM4roAAQ1AkKjuJN4dLCD4YRTYFOmwaScsc=,tag:Mewllgrha7knCZeCBOZZGA==,type:str]
    - ENC[AES256_GCM,data:MqzOFtvviA==,iv:Jkb1xOtdZDfwVQv2i/Sx2RAidGKMXDihmP9alhiuNFE=,tag:d6JSO044QBAdBLJhX5PvTA==,type:str]
    - ENC[AES256_GCM,data:LMFbqlKO,iv:4bPY4k1M/Bu7ShSv8nUqOdouKHQqEa9VT6PxTi67G/s=,tag:XGlnSua88Gk4CSaYJOtC/A==,type:str]
    - ENC[AES256_GCM,data:BgSWpg==,iv:Jkv/FAYpQ9BbJtM66FIVt/W7VRHMhrurHU1P9qVwKEQ=,tag:1bY7aQaNXXt7yTcAMEU2Gg==,type:str]
    - ENC[AES256_GCM,data:RU49X+fOY68cGZ3CE1E=,iv:IDm/07RC66aO35GRqGvtw9y05OAk9Vr2WKdCM4WsT/c=,tag:7dFbLt5BctnOIAA+ETnUGQ==,type:str]
    - ENC[AES256_GCM,data:BfqjGg==,iv:vAMn52DvLXzANxbVFA5g3HmRBwrZyXOjRYpAeZUw74Y=,tag:qQgRmZbG7gPCf5iHxDtJfQ==,type:str]
load:
    - ENC[AES256_GCM,data:e3+BLrHFIFCX,iv:+qwnQkW9cMDPkWDmV7XysOvro8HTV2mYff5aM36lhoA=,tag:K7tS0Li4fKBwxl4fWzDKmQ==,type:str]
    - ENC[AES256_GCM,data:UnqRxg==,iv:EvC25+n6ySo0B89FzTKvgkWF3mebBsbq3BhG+1Tz94I=,tag:ceyMhbarQRXcGfNPu/gqTQ==,type:str]
rebuild:
    - ENC[AES256_GCM,data:YDDqxNVdoHUb9RJnHg==,iv:ZK2DN/WokTdhelxVrlrWsWoOB5FuZEJfaOUzoM0ekx8=,tag:hnm2ekWKbLxQqFOUH44EKA==,type:str]
    - ENC[AES256_GCM,data:Yimeo+UYw1l0FY6Ef1I=,iv:FZDO2oLGhfcHG85UomzscIY3i7CZHwydn61xfYo9cvo=,tag:cxZbbzF0yKqwTJgSFubqbQ==,type:str]
    - ENC[AES256_GCM,data:RKGGfSTeGPgcICgzgockBRf2fak=,iv:glTgp1WWkA/0H3iiPcS3WcAPV1oc8XA+m3cm4wEbK2A=,tag:I7/eEXa9YhO0rf4lGg+6iA==,type:str]
    - ENC[AES256_GCM,data:rPtmDw==,iv:OSRfttdwW6KNLvUo53C13eQ7NseZTBMkR0xGZWjhDw4=,tag:4NvBzUJLL5M/DClHvMTTRA==,type:str]
browse:
    - ENC[AES256_GCM,data:3xQ0xp6qVJJaXU91,iv:nNnavemlY58zd9/FAfXXKtsQqhFKBgYjNE86ODeNuP8=,tag:Se25FRXqsJovKzBjC7Qz1Q==,type:str]
    - ENC[AES256_GCM,data:M8W1WmMtR0eNUTVm+mj5,iv:QfLmfdhbXhWe/UN55QKD8xBSJgyuN1N12+DSPuosZp8=,tag:tjyW7BbMtJyRXlkHSbJKRQ==,type:str]
    - ENC[AES256_GCM,data:trs+rc2bpWU=,iv:6vYQ2fCExPXyniw93SbwAp8pdC5XeoDnMzRQQL8uJLQ=,tag:8U4/7W1iWoVX+slDJE9PRA==,type:str]
    - ENC[AES256_GCM,data:wSZ55w==,iv:g+q6DHNpaQg0YHGmXwxypQYslI/CfzBQry/VS8gUCe0=,tag:p0lrxVKPyoLRv6WGxzOX7Q==,type:str]
edit:
    - ENC[AES256_GCM,data:3J+XtXibOrTsXUqJ8w==,iv:0NDp8Porh5R3N9efkXoqwm2y3jgnK5fZOSWfAkVrkfQ=,tag:M09E91TBxyO3EFzM/mLPEA==,type:str]
    - ENC[AES256_GCM,data:zzXM0jz3VwEknjU=,iv:cX01D6GGjd5z27k1L/nLj1Diet55a4NY68bhT479FJI=,tag:vywRFJiin2vaCbIWgHV09w==,type:str]
    - ENC[AES256_GCM,data:0Oa8HQ6ebwstGXXJ,iv:JDjJol6XYPXvpKTTPpEen4LT5AeFxtGR5uT9ykTazSM=,tag:5nXF79z/aUX9jUua730Qug==,type:str]
    - ENC[AES256_GCM,data:geL9qHSMiNdB,iv:D+7ZTcS9SRa1gfADPZoPSRZN06pAM8BHIDbGfcIwsho=,tag:nqMB3ZNQbkH7UTFLC0xEtg==,type:str]
    - ENC[AES256_GCM,data:B0PSp3dBhA94751VMy4FJA==,iv:rA16V3mhnrOpY5a6s1YH8eBJqvdiIaj796GeYEFl8Ic=,tag:R1lnNnoYTnb9jgixQ0Lkgw==,type:str]
    - ENC[AES256_GCM,data:HUBvxf0oy/cetiAlE7kfo08=,iv:jK8AFxEvosTrm1e0ICJqlfYoZvxxDYnMUJtJdXXoNNg=,tag:soZlG/WaQYcGLRKPjH48kQ==,type:str]
    - ENC[AES256_GCM,data:chSw/hcZKs4ZZ9sVJktgYXk=,iv:6xp4xKC8lA9k0WknSvN8JYATQKWAdtM86/FJM9xa4+8=,tag:3OWbVfgufU7ujVZE411CFw==,type:str]
    - ENC[AES256_GCM,data:TypF+A==,iv:TY7cmikhoF5uCFoeRQXh91Nrh1aDQG3hwgaIfRcsAyQ=,tag:+CcUMsnAbWClaHiYFWtsjA==,type:str]
update:
    - ENC[AES256_GCM,data:MSpN1eAUFLOTQXb9,iv:nmOiviJ0FXvJQkVj0cULI9F/ZTth77AIqQkemp3AMhM=,tag:2aR3Xbk+7AnBpoDWVkRNkg==,type:str]
    - ENC[AES256_GCM,data:hF11Qr8mWj+Dei4=,iv:ZbXo9iwmVjpkIKSP26ih42x/Nd7j6pNrRUWJa9kxFg8=,tag:cklTleawG3bDixLaFYJy1g==,type:str]
    - ENC[AES256_GCM,data:B3fRCg==,iv:jxoNuwKPnaXSUDTbG7tVOhZDmXSbkzh7rv7r2E7+CH4=,tag:+151YV8/VClrAPIZkqkdYA==,type:str]
tasks:
    default:
        cmds:
            - ENC[AES256_GCM,data:UL0NUBScXO998XL91IIEMM72zxp1Ww2mWDfvnYg6U1jc1+NSVUpX9OAWfXp5aEMu+RSpa4ss,iv:MOz/2wtz6WrzkTTzib5k3Au+z51+F5eku7gxoLtuSrY=,tag:IatpMObfus900eT59BIO3Q==,type:str]
        silent: ENC[AES256_GCM,data:peo3mA==,iv:rF178fkyiKK0q6vD2Uq/7FAeFazJQqD1FjLUqB2gnmA=,tag:u03pa69t+4qDoGcBG6eNvg==,type:bool]
    rebuild:
        cmds:
            - ENC[AES256_GCM,data:O2hWjbEM17Y9hp4mRFU6hB5s8hLlXb6y/5Vygbx8URy+bX1IdriwQy7iUsfd5LaVf2S+jG/P77oz,iv:+l73atuntQeKfu0gaS6p/6eywlmlaKA8GpiQq0IbWY0=,tag:tRVvZVZrhtPGzq5TmteurA==,type:str]
    nixos-rebuild:
        cmds:
            - ENC[AES256_GCM,data:RrfXtfIuBB2bypTz50E47z6kBi3UHr8ME5oPNNN6YSGPZAl2m+zPoKDhioOW9g==,iv:EVA3KtY9oJO5Mrb6qReCqYuPRbm7S9Xu3H+6sNJe8XM=,tag:LaR0JQOmZpIncSJ7wnZ/ew==,type:str]
            - ENC[AES256_GCM,data:vaHNIxMHvbLw0HWMIA==,iv:3sR2LnHBySj2xeZCL7ypJ3FbfFyasrNuFipEDFQdjNs=,tag:qVWhiq5Koe/qVLGKwUQzjA==,type:str]
    darwin-rebuild:
        cmds:
            - ENC[AES256_GCM,data:lVbN95Y7LQSdsCog9/+7rQC8l31Wq8mkNwOEOhbwh2+Mw638vIZFzXUSYfqlTsMCQlq+,iv:/kO10/OUMVFRivCzoPHTsiptqnDH3x+JmMDATWrQJwc=,tag:pwNGdcrH/KSHk7e4SSzKMg==,type:str]
            - ENC[AES256_GCM,data:4YXrzg1g77D7UzqaUQ==,iv:Tw63OdHjPYd8Ts+Emwl/nVnP2qB80Zp8h0UEJE73PSo=,tag:xBWm/2cTJQ9O+hKlllOt5Q==,type:str]
    home-manager-rebuild:
        cmds:
            - ENC[AES256_GCM,data:UDl78eLI1FqAL1qKbBdEvIo+5UMBEgL79+JAp2/m1nIptJYQKuOBBVSdyVM=,iv:SORO9c8H4LQxwIcJajwR/psiJAA+sLigXt8Pql1tSuo=,tag:afof0hQ+fcwk7pZjIeHZ8A==,type:str]
            - ENC[AES256_GCM,data:9p+kLQSHm1K9f8Ob4A==,iv:JA5eUT2CynB4iGeB1/8PuCbPRgRsmzm7QhgcxbBgrz0=,tag:JMDwx9S+5rxnTmAMBlS0RA==,type:str]
    load:
        cmds:
            - ENC[AES256_GCM,data:/ubzVfdMd8sQCjSogb0bOMB91Phj5ptkYR2BKtr3mj9ilDoNsbQ4pZgx39S0dcMd+QlQ9Qhw,iv:+LAH+OKLnGeB7bg4cHfqwc5iS5X+AX+gQQ+nw98U+4U=,tag:aVuMxE4es/2LXy2cKNQJ0A==,type:str]
    load-groq:
        cmds:
            - ENC[AES256_GCM,data:PS0b0tUy8P07iw3fLRvt9i4byekFJqD1ZP3XhgUr8zJGflZBq5nk6+yQ44dwtaFhvKmhUERewRRC6bAK2gyuWPNQRuJxwS/myTnJ8KejQZLzJORGyd9TRHSVV2sQi4NJ0yVx+pnSo/eDJnix6I8IApWbzsMLOgZG,iv:wgkE8nNZ2x2KfnYX6/GNLJ8pwWnMV+pMhxlaMhLWKs0=,tag:owJlTkls1FYnc7+JhWlTrg==,type:str]
    nwmount:
        cmds:
            - ENC[AES256_GCM,data:xTpVaipp9yS465sJaIQPklDLE8Yh0csS+INQ3bqi6lohaOpzMVb3J1mX9Kb15dunbYYsV5GwKSp0v+SZUU0AGW8LgQY4aDxfQsjdECk2Np4iQqMta41U2zyrL/uNdz0SXzCjA2IE,iv:aMaw1cVDQFVqlp0tmvf7JSQgVQbVWjqomhtPX14XiIc=,tag:3+aD4HKHaWwf3dj33URTNA==,type:str]
            - ENC[AES256_GCM,data:/0W1tZfjzJ4ZoA4F5UX8ja8aG10qZwhXWmHIkcnQmth34kOw+cI5O9XTtLl5MwHnTAE3KevfasPiIs6OlqkrcMikttB9joxZE7QPzzTjfmUSlX0tM/P3zdJgRCOLNdLhVJvB0FXu2/368Q2MdvQi+BPRaQ==,iv:i2diudOOL5Of9zjivFaHGT8dAaXW5rDdTS/z+lHwbqg=,tag:riDoBbO/1zDyUVEqANkTGw==,type:str]
            - ENC[AES256_GCM,data:7jJOaHcbHV1idaK3Zrm1q8GCHPlMUo0e3v8lTDanN/9mFB/w7WYeUM0BKZkVMi2mI8TDQTQ78ssP1tg6U3xqx8MfWFdYDc6hJIDL+nV6Drp4xf5EJmRuIwHxjWDKOnu11GMx2Ai+sDyAOOlvp91IseTOAdYItYkSrg==,iv:IlB4/W4pU6VNNw5f4vs+cFhibW+T5tASjX9kgJE3YOs=,tag:wLvAUgROI6mJXk725p98PA==,type:str]
    browse:
        cmds:
            - ENC[AES256_GCM,data:abns0B7JEaZRuRuNq/HUgPPj+yc2qwhKzw4lfjXjnu09QoqT7QhYWaS9+SGXyyymLhEgs3Jyfhs=,iv:6S6zjrOsiBb3kJZEqxrduLPezcN0IKrHp1E19YXfkfg=,tag:nOnAk4+07VktJwYPVPrnHg==,type:str]
    browse-notes:
        cmds:
            - ENC[AES256_GCM,data:/cC8c25/e7DGpYnBHTuOXNEzxCtr+O7Hze6LZL6gwdinuTxQwlUf/N5zSAx36RM=,iv:XtBaG+tQFD6PsmFhnxIwaXAFOc4DGt85pp1UHf3NngE=,tag:s3hvYlPpVxCGB+KTW/VR+Q==,type:str]
    browse-internet:
        cmds:
            - ENC[AES256_GCM,data:KUyqTWS5JIhBbcTfjzwVDPkxKw/3oWE3Lkli,iv:etboXBDRxdNhLX/f/iv8Z3atpHliduxDbU5HYtIG7Ac=,tag:/EFIVZ48h48peJPZFGA2IA==,type:str]
    browse-projects:
        cmds:
            - ENC[AES256_GCM,data:45/OdGHRQdzs7VnuqbGlTEt7Y/g3Y1CK02DJjqxJvu4=,iv:bB4h71GEE/yb+I7R5kqvZqu81aAyZucLpLl3ykEeWFQ=,tag:93VYxFmC9/JvI3FcVxg/KQ==,type:str]
    edit:
        cmds:
            - ENC[AES256_GCM,data:2sbvcy5Un3TnvmBL37ba30o9fs4vqiK+qHrhH7SkAgehHSSDE/qkcAsSaDPBn4Nsqckp0Ati,iv:/vDJaXqC+2FOyIxiSSQDOSrA4GiVKB2wMBC4G72PfmI=,tag:res8jYn/Lm0/4/TgLJoCHg==,type:str]
    edit-taskfile:
        cmds:
            - ENC[AES256_GCM,data:AE5M1m8WTjAzX+J+uX6zVIPEm0ukhKBRGlgqwFPBX7zMe6hZm7szsZi7uhcLIRX7,iv:EF3pd6lyv+DEWOrLl3ojeTEJcibKQUQ2UQ0xj+SOvVg=,tag:bNJtei01IXQKZBFb6w2omQ==,type:str]
    edit-global:
        cmds:
            - ENC[AES256_GCM,data:OlaLP26wohd029qsumTmksv6i7jHThbhQkaw9x09JA8=,iv:EdEdX2g1MW2MsSVU1w54NgtiwTw6Ga+PP+mjQ6Yw1/w=,tag:o7zkdFO5s+fVgiLj0rvMvQ==,type:str]
    edit-secrets:
        cmds:
            - ENC[AES256_GCM,data:jAR5bbulX/SOe7TzTP8w6kRIkT2cW8b67YcOYCl75hL+q/84T4encgfCNQsq7jg=,iv:zhnlfuy0WM8h1odJ+/w1bhgi4VBeJDwVbb6UI/qnEGc=,tag:40pqicFF03mFBwVNyROQ6w==,type:str]
    edit-sops:
        cmds:
            - ENC[AES256_GCM,data:26yvI6tvWBEkO26TgOgy,iv:4HYMqnB11IyltIKP7hBgxWHQx7Dwq2bY5MMzGxETViE=,tag:a9M6vd3E8lYfrINt08cKDg==,type:str]
            - ENC[AES256_GCM,data:6s7ENhCUBXRUaAhjNGyg+E7jDHk=,iv:Wnhc6Y0Em8EVI+hPqrRYKy6Cf1lgqDL9P6vFzfy80yc=,tag:9hgHnkFkDy5xhZOnZIBG6g==,type:str]
    edit-sops-config:
        cmds:
            - ENC[AES256_GCM,data:he3v7B0humaoZnOwugWriMXCSIW58Kyw0Py42LiU,iv:uypOT5zdraus1SEkif9BrtAGdBX7FSXWa9/J5Uv85Ds=,tag:Q7KOIHPub284iVj3dxx/BQ==,type:str]
    edit-home-manager:
        cmds:
            - ENC[AES256_GCM,data:OpelUoQ2aik6t10Vu6UfpUe5dQdX90x3fpNbIyWX,iv:2QnbPua/xF2r/Dki4L3PRHdgkvwNw+uM/pr+zSXWT1A=,tag:bfcyT5HJKL2fvr9GC7xsWA==,type:str]
    edit-shell-config:
        cmds:
            - ENC[AES256_GCM,data:c6nEXMW1w6DzzdR6Tr0E6021B82lwVAnCcNeLqEB6MpUPr3ckrgr,iv:vbIrLpRKz5I/TzO4yZvXyNRZ7C3AHcmQkw02wNdG3VM=,tag:XU22RYVmFFNpOC53+WNriA==,type:str]
    git-quick-push:
        cmds:
            - ENC[AES256_GCM,data:mgJb8IZMNUp5u8yoK5RFQxI=,iv:SY3d/P9B60roz3rOVM8SCbZ3K/DQUuPCsNtefIH4YHU=,tag:Qfb2ELUmrP9lOV2+FaS2Yw==,type:str]
            - ENC[AES256_GCM,data:n7ZTfsz7BOLR,iv:DmGDEf02hgC58z0SjOd8AwSb6nGau5A+rc4adhSIkJY=,tag:Tfe39DPObtgmH5jneNs6tg==,type:str]
            - ENC[AES256_GCM,data:oC3sN/1o1xjnUxakFBgCGhbIo7CvE2jO+QwiclM=,iv:T0JEYSzkfXGOu1Dly50XxB3uel7XxFuPaX+ZZwenoY0=,tag:3wC9dXW29zxb/CZtUkm1XA==,type:str]
            - ENC[AES256_GCM,data:/nJV++LegKdhn4M=,iv:dDhDj10tAc1HyIdBlK2DcTSOoQT5hipmhhGq/UqWNyI=,tag:O7y/plVpAVTHGrS+G/qo4A==,type:str]
            - ENC[AES256_GCM,data:wzfgJFoaSIaKENDnEQ==,iv:7JNXuBHZMMmnElllEAOPcIMuycSG1ei1Wf3KCm74lRA=,tag:UZivCgg8MMn3U3hkFjg1/Q==,type:str]
    git-quick-pull:
        cmds:
            - ENC[AES256_GCM,data:aPBABuMkD3E=,iv:t3ZGYntz7QoXZR5g139ZIElTNDfqbziUMpysDJUyihE=,tag:lfhiIwdZv2GQ30ISP9GXkQ==,type:str]
            - ENC[AES256_GCM,data:SRbZ08FXcrVfSOn+YQ==,iv:rmQba6G2WsNjDY1Pl3KcGchyPmUm2jVuVrgaZKrjsTo=,tag:Txf81jF8qW8FfGpkegc2HQ==,type:str]
    update:
        cmds:
            - ENC[AES256_GCM,data:PAVRBBk0RWLPUo5sIqC/2wDHHg1lu8h1SNLrRVTWDhq3zra1U0G69v+ey/B9eBdfWq/n7Ba0syg=,iv:8p1XGDVjjfT8hx7n6Y55PlHB9MEC33rDedRXZtp85vE=,tag:9UVTJNOuVLEqPEwf4MKKkw==,type:str]
    update-flake:
        cmds:
            - ENC[AES256_GCM,data:72i4jyWFKB23tq7voCkydw==,iv:YCzcvFa0wSv4c6BUQ43AN5YcUPyZ7RSv4OrffEVZBhE=,tag:ZzEDZq7bOXdNWUzyQ1NdsA==,type:str]
    updatekeys-sops:
        cmds:
            - ENC[AES256_GCM,data:Ccvd3LsBTYl8OPW3xwO90aL73WPqLgi3huu9Yl4tKM05lEO+n/Uz5ekz6xoElBz4rFNFRVA=,iv:U/ZHMuqNEueBdvLG8+0zxcqSCQYgtIUm8A/hVFzIqYU=,tag:9xy0t1U4tsQV1vW/eYCCXw==,type:str]
    exit:
        cmds:
            - ENC[AES256_GCM,data:cdhg0Q==,iv:DoOPcF7u5nXIGp3mDC8iBXQODcaeGpw6Mmlxiqm2Nko=,tag:XBYoxdozxAqaSXLCGQkRrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tsv2lurpjzyx9ng6hcc4dff23lvv7tqkyyxz5zlpx32egu2c9vfql9m008
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFpXanh3M2oyTTZwcDg4
            RWJ6RjN4bnhBSmx2Vy9DcTJFYTJLOEtWNlNjCld1QklXRkVzcnJadlN5MGd0Mlcx
            UlRoWEh2YWhnbGR3RklzVG9XK1Z6Z0EKLS0tIHNSbWJFazZ2TnVXVjR5NzZYZk5W
            UHREcE9CMmwzODh0Um00dWdBb2FSY2MK0drNd+ot356Anau7StTTEOHWa03+xnJX
            y5q/V60bK9uai+fs2AO0AcYYVVQRIK2806gQe+ap0Eq2+slfXfIOiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywan3hwg4v306e3gk4sjzfvjfxru432kgr3xlmwu77nkhgsjmfuqr7lktd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S2lMc1ozaVh3SE52a2tz
            S3l6QTVZRkhjeXZFTlViVE42bnU0eFBxQ2hZCm4rcFpUaXRjQm1wQWh3VlpTUmpJ
            WFhnMEFDblgrWXZFOXJvSVBNclBOdzAKLS0tIEhSbStKc1pwdWt5cStxN202d0tL
            emtIWER5N1o4VDNOYmhTRFdVVlM2VUEK9oUDkrF1oyYH49ZzrdqYx1zrg4kvtX/f
            GiSi6wuSUaY9KIGHClOHvPlOp9zfkZPLA4hNlfAa6tOU8mZSNiV6uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15ptau7jyv6kcwz39vcfzxpw95p97l5r7uywkcl5g83gqxuhh7q4saggagy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTF6d21ZamtSaHl4Y0gy
            YVNrZE5OcjJza2MzSURXUmNMUzJUS3YxQ1h3CnpNRnNpcmFPNklvSG8wZ0pScnVz
            RjV1VnBMajRuQXZjY01uYUNySjhTNmMKLS0tIFhCMUpWTlY5ODd5K3JzUXNyQTVp
            L3BZTnZwVlNMaCtHUkVYWXpYa1lmM1UK+f9OXA7s60lLETmMRJW0KuAl0ngomQlH
            y+G9Qa9X2jKs5HScAKbMpDnY3LK/x6lxOCRqfBDsB1ZAD17mM+EfDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezs5s0mx7pcmv0cq6lhvxqtrgx9shrenpxuqyny3m52rg4a6vuxq9ucd7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra29OZDdZclc1M1B4cXJM
            QkszM1JoRDB0bEV1dDVKSVZaQWZ6YmZEcFV3CndLM2pSbUhPVS9Fbi8ybi85ZFRO
            K1VsdmJKU2h4TmxxcjdCLzRFblNMM0EKLS0tIFNhUHdpeDd3OENpeUsrTkRlTy9C
            R2RuT1F6WE5aVHF0cnB0ZkV1S2QxQncKPYioI3DP00nOpmJJclwkVGXT7M5CrtOl
            UUqhCwHK/9WaPmPANeOnvWYNEZOi4mNtZ0jTiXGeNAWKqc03+1H/XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T11:42:54Z"
    mac: ENC[AES256_GCM,data:+xiVc9HhhR/1gPBhHE8AzxvEz0kGxh+IbkMBguAqlxzBBNcnhmNeoyXdMQLHfHNswJfMi6czTq8OfLonOiqB21HMAjU1TaaRnFUZ4QqYD6a1Bm2ZaMWvkTewxi4mp4NQyw0Okn22iI447tzl/cYiLuere1FwxAwaLC8lgiECrz8=,iv:msW+mhEQObqiR0GhwkOV+JaRX0+fzfiPWNgyeimQN4I=,tag:NZdW3oQYmIb5Wq2n4l6Z7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
