# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@root" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23C4-8C55";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@snapshots" "noatime" "compress=zstd"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/68e7dbb7-22a2-4441-9cbd-b803199226b3";}
  ];

  # --- 2TB data drive (migrated from decommissioned thinsandy host). ---
  # /dev/sdb2 uuid e8622c5d-270e-47fa-a1ec-3aca0ef95d8e.
  # Subvol layout: data / public / private / transmission.
  # /nix and /swap stay on the 1TB SSHD (sda3 / sda2).
  fileSystems."/srv/data" = {
    device = "/dev/disk/by-uuid/e8622c5d-270e-47fa-a1ec-3aca0ef95d8e";
    fsType = "btrfs";
    options = ["subvol=data" "compress=zstd" "noatime"];
  };
  fileSystems."/srv/public" = {
    device = "/dev/disk/by-uuid/e8622c5d-270e-47fa-a1ec-3aca0ef95d8e";
    fsType = "btrfs";
    options = ["subvol=public" "noatime" "compress=zstd"];
  };
  fileSystems."/srv/private" = {
    device = "/dev/disk/by-uuid/e8622c5d-270e-47fa-a1ec-3aca0ef95d8e";
    fsType = "btrfs";
    options = ["subvol=private" "noatime" "compress=zstd"];
  };
  fileSystems."/var/lib/transmission" = {
    device = "/dev/disk/by-uuid/e8622c5d-270e-47fa-a1ec-3aca0ef95d8e";
    fsType = "btrfs";
    options = ["subvol=transmission" "compress=zstd" "noatime"];
  };

  # Bind mounts — NFS export roots + unified media path for Jellyfin/Plex/Immich.
  fileSystems."/export/data" = {
    device = "/srv/data";
    fsType = "none";
    options = ["bind"];
  };
  fileSystems."/export/public" = {
    device = "/srv/public";
    fsType = "none";
    options = ["bind"];
  };
  fileSystems."/export/private" = {
    device = "/srv/private";
    fsType = "none";
    options = ["bind"];
  };
  fileSystems."/media" = {
    device = "/export/data/media";
    fsType = "none";
    options = ["bind" "x-systemd.requires=srv-data.mount"];
  };
  fileSystems."/var/lib/immich" = {
    device = "/srv/public/immich";
    fsType = "none";
    options = ["bind" "x-systemd.requires=srv-public.mount"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
