# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@root" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23C4-8C55";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/4c2a62aa-b9ff-49c2-bc3c-768563b3301c";
    fsType = "btrfs";
    options = ["subvol=@snapshots" "noatime" "compress=zstd"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/68e7dbb7-22a2-4441-9cbd-b803199226b3";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
