# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_acpi" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules= ["crc32" "f2fs" ];
  # boot.initrd.extraModules= ["crc32" "f2fs" ];
  boot.initrd.includeDefaultModules = true;
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c59baab5-2e5d-4b64-8c21-29866e4d615b";
      fsType = "f2fs";
      options = ["noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/75B1-4591";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aa9b0e7f-9ac4-4a82-833a-90dc5bbbca40"; priority = 10; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
