# DEPRECATED: Part of orb-cassini (see configuration.nix for context).
# Retained as a reference only. Originally auto-generated incus guest config.

_:

# WARNING: THIS CONFIGURATION IS AUTOGENERATED AND WILL BE OVERWRITTEN AUTOMATICALLY

{
  networking.hostName = "orb-cassini";
}
